zbycz/osmapp

- src/components/Panel/FeatureImage.js
- src/services/images.js
Attempt to add general photo-db "Fody". It currently covers mostly CZ or EU, but author is open to worldwide usage.
See: https://openstreetmap.cz/git/tom.k/Fody/wiki/
Fody API returns correct CORS headers only for `Origin: openstreetmap.cz` 
Server side rendered page is fetched using node - but click on any other (i) icon and see error in console: https://osmapp-git-fody.zbycz.now.sh/node/394820093#14.24/50.0975/14.3104
> FeatureImage: add Fody photodb

- public/oauth-token.html
- src/components/FeaturePanel/EditDialog/createNoteText.ts
- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/SearchBox.tsx
- src/components/SearchBox/highlightText.tsx
- src/components/SearchBox/onSelectedFactory.ts
- src/components/SearchBox/renderOptionFactory.tsx
- src/services/intl.tsx
fixes https://github.com/zbycz/osmapp/issues/55
> Search: use maptiler geocoding api

- src/components/FeaturePanel/helpers.tsx
The key [fhrs:id](https://wiki.openstreetmap.org/wiki/Key:fhrs:id) is used in the UK to give the id of an establishment in the food hygiene database.
Linking to this means that users can check the food hygiene rating of the establishment.
Future work would be to fetch the rating and show that in the card.
> Make fhrs ids into links

- src/components/Map/styles/basicStyle.ts
- src/components/Map/styles/layers/contruction.ts
- src/components/Map/styles/outdoorStyle.ts
https://osmapp-git-contruction-zbycz.vercel.app/#16.30/49.6688/18.3240
-----------------
For future reference, there is a data browser availible here: https://cloud.maptiler.com/tiles/v3-openmaptiles/
I have first verified, that the lines are in the data. It can be seen, that its the `#transportaion` source-layer, and can be selected by `class === motorway_contruction`.
Then I opened their [Style Editor](https://cloud.maptiler.com/maps/style-editor/), cloned the Basic style, and made a copy of the `motorway` layer. Then I played little with the paint settings.
Fixes #29
> Map: add motorway_construction layer

- src/services/images/__tests__/getMapillaryImage.test.ts
- src/services/images/getMapillaryImage.ts
I should point to the selected place but it's not reliable. Currently sometimes points to it, but sometimes it shows the opposite direction.
should fix: https://github.com/zbycz/osmapp/issues/97
> Update to Mapillary V4 API

- src/components/Map/styles/basicStyle.ts
Hello! This is my first contribution. My end-goal with osmapp is to use it at work. I am a public safety dispatcher, and I use Google Maps constantly for roadway geography.
I'm looking to help build osmapp to a place where it can replace Google Maps for my workflow so I added some key details that I use every day at work that were missing from osmapp previously.
Thanks! Let me know what you think 👍🏼 
- Added motorway junction labels
- Adjusted spacing on labels slightly to compensate
- Added oneway icons for highways at close zooms
Before:
After:
> Update highway labels styling

- src/components/Map/styles/basicStyle.ts
Just fixing a mistake from before. Not every junction should be labeled this way.
> Junction label correction

- src/components/FeaturePanel/FeaturePanel.tsx
- src/components/FeaturePanel/PublicTransport/LineNumber.tsx
- src/components/FeaturePanel/PublicTransport/PublicTransport.tsx
- src/components/FeaturePanel/PublicTransport/PublicTransportWrapper.tsx
- src/components/FeaturePanel/PublicTransport/requestRoutes.ts
- src/services/__tests__/osmApi.test.ts
This PR partially fixes #168. When a public transport stop like an bus stop, train station, subway station or  tram station gets clicked the user can now see which train, bus... lines hold at that stop.
> Public transport labels

- src/components/FeaturePanel/PublicTransport/LineNumber.tsx
- src/components/FeaturePanel/PublicTransport/PublicTransport.tsx
- src/components/FeaturePanel/PublicTransport/requestRoutes.ts
- yarn.lock
This PR addresses two significant issues and introduces improvements to the public transport labels:
1. Background Color Adaptation:
- Previously, the background color of the labels wouldn't adapt when the color is specified as a word (e.g., yellow) instead of a hex-value. This PR fixes this issue by implementing dynamic color adaptation.
2. Overpass Query Enhancement:
- The old overpass-query to retrieve routes had multiple problems:
- It sometimes displayed routes from stops that were closer than 150 meters to each other, leading to incorrect information.
- On the other hand, it failed to display all routes when a stop was more than 150 meters away from the actual node for the train station.
- To solve these issues, this PR introduces the use of the relation stop_area to retrieve …
> Public transport labels fixes

- src/services/osmApi.ts
- src/services/osmApiAuth.ts
Use `api.openstreetmap.org/api/` -and HTTPS- instead of `www.openstreetmap.org/api/*`.
(Is: https://github.com/openstreetmap/operations/issues/951)
cc: @zbycz
> Switch to api.openstreetmap.org API host

- next.config.js
- pages/_document.tsx
- src/components/App/App.tsx
- src/components/HomepagePanel/InstallDialog.tsx
- src/components/Map/MapFooter/LangSwitcher.tsx
- src/components/Map/behaviour/useOnMapClicked.tsx
- src/components/utils/MapStateContext.tsx
- src/services/intl.tsx
- src/services/intlServer.tsx
When no prefix is detected, the app is used as before (cookie or accept).  It leverages the nextjs's default locale called `default`. 
When prefix is detected, it forces the selected language and sets cookie.
-----
This could 
- help Google to discover other language versions
- and also users could use it link specific version like `osmapp.org/cs/node/123` (not that useful)
Alternative urls:
- `osmapp.org/cs/node/123`
- ~`osmapp.org/node/123/en`~
- ~`osmapp.org/node/123?lang=cs`~
- ~`cs.osmapp.org/node/123` <- not sure how to do on vercel~
~Questions:~
- ~no prefix = english OR autodetect?~
- ~use prefix/query only as setter&remove OR leave it in app consistently~
> intl: support language prefixes for all URLs

- pages/sitemap.txt.tsx
Since we have id-tagging-scheme in place, every feature URL should eventually be submitted to search engines. 
I started with items having `name=*`in Beroun. Their urls are here: https://osmapp.org/sitemap.txt
```
[out:json][timeout:25];
// [out:csv(::count, ::"count:nodes", ::"count:ways", ::"count:relations")][timeout:25];
area(id:3600442333)->.searchArea;
(
nwr["name"](area.searchArea);
);
out;
```
> general: sitemap experiment

- .dockerignore
- Dockerfile
- next.config.js
* Replace docker file with template from https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
* Uses node 18 instead of Node 10 which is no longer compatible
* Add the option via ENV to build to config standalone and use this for the docker image
> Fix Docker Build

- src/components/FeaturePanel/ObjectsAround.tsx
- src/services/getCenter.ts
- src/services/overpassAroundToSkeletons.ts
Causing ERROR PAGE to render for any coords clicked.
> ObjectsAround: fix - use correct `getCenter`

- package.json
- src/helpers/featureLabel.ts
- src/services/osmApiAuth.ts
- yarn.lock
Oauth 1 is deprecated
Oauth 2 here: https://github.com/osmlab/osm-auth
> osmApi: use OAuth 2.0

- __mocks__/next-codegrid.js
- package.json
- src/components/FeaturePanel/Coordinates.tsx
- src/services/osmApi.ts
- src/services/types.ts
- yarn.lock
Using [next-codegrid](https://github.com/zbycz/next-codegrid) package.
TODO: unfortunately the service worker caches all the tiles (we can live with 1.5 MB though 🙂 )
Modification of the [codegrid-js](http://github.com/hlaw/codegrid-js) library for use in Next.js.
- bundles all tiles as javascript chunks – both for client and server
- this process adds 10 secs to the `next build` (TODO: optimize - store in /public ?)
- output size is 10.5 MB (see .next/static/chunks), or 1.5 MB gzipped
- first resolve takes ~40ms (both client and server), subsequent resolves are instant if it falls to the same tile
- fetches 35kb for worldgrid, then 100-300kb for tile (or 13kb gzipped, then ~50kB for tile)
> general: add offline country resolution

- README.md
- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/SearchBox.tsx
- src/components/SearchBox/onSelectedFactory.ts
- src/components/SearchBox/options/overpass.ts
- src/components/SearchBox/options/preset.ts
- src/components/SearchBox/renderOptionFactory.tsx
- src/components/SearchBox/types.ts
- src/locales/cs.js
- src/locales/vocabulary.js
- src/services/fetch.ts
- src/services/overpassSearch.ts
> SearchBox: add custom overpass search

- src/components/FeaturePanel/Properties/getUrlForTag.tsx
Like discussed in #378 this makes social media usernames clickable.
- [Instagram, Pinterest, Tiktok, Youtube](https://osmapp-git-fork-dlurak-contactlinks-osm-app-team.vercel.app/way/1257446762)
- [Facebook](https://osmapp-git-fork-dlurak-contactlinks-osm-app-team.vercel.app/node/11396781351)
- [vk](https://osmapp-git-fork-dlurak-contactlinks-osm-app-team.vercel.app/node/312453742)
- [Twitter, Matrix, Mastodon](https://osmapp-git-fork-dlurak-contactlinks-osm-app-team.vercel.app/node/3342079613)
> FeaturePanel: make social media usernames clickable

- src/components/FeaturePanel/PublicTransport/requestRoutes.ts
* This tries to support nodes which are not contained in a stop_area relation but directly in a route relation, example: https://www.openstreetmap.org/node/11035607130 as of version 5
Fixes #387 
//edit:
Examples:
- stop relation /node/24569897
- without relation /node/11035607130
> #387 Support Public Transport mapping without intermediate stop area relations

- src/components/FeaturePanel/Climbing/ClimbingPanel.tsx
- src/components/FeaturePanel/Climbing/ClimbingRestriction.tsx
- src/components/FeaturePanel/Climbing/contexts/osmToClimbingRoutes.ts
- src/components/FeaturePanel/Climbing/utils/emptyRoute.ts
- src/components/FeaturePanel/FeaturePanelInner.tsx
- src/components/FeaturePanel/OsmError.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
climbing not allowed on crag
climbing not allowed on area
climbing restricted on crag
> climbing: Add climbing restriction + show authors on routes

- src/components/FeaturePanel/Climbing/GradeSystemSelect.tsx
- src/components/FeaturePanel/Climbing/RouteDifficultyBadge.tsx
- src/components/FeaturePanel/Climbing/RouteDifficultySelect.tsx
- src/components/FeaturePanel/Climbing/RouteDistribution.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListRow.tsx
- src/components/FeaturePanel/Climbing/TickRow.tsx
- src/components/FeaturePanel/Climbing/utils/grades/routeGrade.ts
- src/components/MyTicksPanel/MyTicksRow.tsx
- src/components/utils/UserSettingsContext.tsx
- src/services/my-ticks/getMyTicks.ts
**Allows to show original grade from grade system select:**
**Show multiple grades in the table:**
there are few UIAA routes:
rest is in french:
**Show original gradings + converted value according to selected grade system:**
Zebra doesn't have YDS, so it's converted:
Zebra route has UIAA grade:
Kojot doesn't have UIAA grade:
But Kojot has french:
Zebra has also french:
**We can sort it in My ticks according to visible items:**
> climbing: More precise grading system

- src/components/SearchBox/onSelectedFactory.ts
- src/components/SearchBox/renderOptionFactory.tsx
- src/components/utils/SnackbarContext.tsx
- src/services/overpassSearch.ts
Sentry Issue: [OSMAPP-ZT](https://osmapp.sentry.io/issues/5734120987/?referrer=github_integration)
```
Error: Objects are not valid as a React child (found: object with keys {content}). If you meant to render a collection of children, use an array instead.
at o (app:///_next/static/chunks/framework-8c133e52ff743bc3.js:9:52797)
at uu (app:///_next/static/chunks/framework-8c133e52ff743bc3.js:9:71062)
at i (app:///_next/static/chunks/framework-8c133e52ff743bc3.js:9:121187)
at oO (app:///_next/static/chunks/framework-8c133e52ff743bc3.js:9:99022)
at 64448/oF/< (app:///_next/static/chunks/framework-8c133e52ff743bc3.js:9:98890)
...
(5 additional frame(s) were not displayed)
```
> SearchBox: fix broken showToast in overpass search

- src/components/SearchBox/onSelectedFactory.ts
- src/components/SearchBox/utils.tsx
Sentry Issue: [OSMAPP-H7](https://osmapp.sentry.io/issues/5716385613/?referrer=github_integration)
```
Map cannot fit within canvas with the given bounds, padding, and/or offset.
```
> SearchBox: make fitBounds work on smaller screen

- Dockerfile
Project was updated to node 20, this makes the `Dockerimage` compatible
* we switch the image to a Debian based one, because some node binaries are not available directly for alpine and would need to be built
The docker image is currently not automatically build in this repo, we might add an action like this:
https://github.com/OpenPlaceGuide/osmapp/blob/opg-master/.github/workflows/docker-image.yml
But we can also leave it semi-supported in here and I will take care of it, when I spot problems.
> general: Update Dockerfile build node to version 20

- package.json
- pages/_app.tsx
- pages/_document.tsx
- pages/api/google-analytics.tsx
- yarn.lock
> Analytics: Update without new dependency

- src/components/SearchBox/onHighlightFactory.ts
> SearchBox: Fix broken flyTo on mobile

- src/components/Directions/DirectionsAutocomplete.tsx
- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/SearchBox.tsx
- src/components/SearchBox/getOptionLabel.tsx
- src/components/SearchBox/onSelectedFactory.ts
- src/components/SearchBox/options/geocoder.tsx
- src/components/SearchBox/options/openstreetmap.tsx
- src/components/SearchBox/renderOptionFactory.tsx
- src/components/SearchBox/types.ts
- src/components/SearchBox/useGetOptions.tsx
- src/helpers/utils.ts
It is now possible to search for OpenStreetMap ids in the following formats:
- type + id: `node/660921`, `way 10568134` or `relation,406091`
- url: `http://localhost:3000/relation/406091#17.00/59.9722/10.7203` or `https://www.openstreetmap.org/node/660921`
> SearchBox: Add support for openstreetmap ids

- src/components/FeaturePanel/Properties/TagsTableInner.tsx
- src/components/FeaturePanel/Properties/renderValue.tsx
- src/components/FeaturePanel/PublicTransport/LineNumber.tsx
- src/components/FeaturePanel/helpers/color.ts
- src/components/SearchBox/options/openstreetmap.tsx
Highlight colors by providing a background color for the colour tag.
- I'm really unsure about showing the hex code after a word.
- Is it better to use a background color like in this pr or just a small colored space like osm.org?
- I think it is preferred to show the values as they are in osm. But if you want it would be easy to convert the hex codes to human readable color names as I have developed a library for that.
> FeaturePanel: Highlight colours

- src/components/FeaturePanel/Properties/Direction.tsx
- src/components/FeaturePanel/Properties/renderValue.tsx
Add a arrow for the direction tag. This fixes #590
> FeaturePanel: Arrow for `direction` tag

- src/components/FeaturePanel/Properties/Direction.tsx
- src/components/FeaturePanel/Properties/IdSchemaFields.tsx
- src/components/FeaturePanel/Properties/TagsTableInner.tsx
- src/components/FeaturePanel/Properties/helpers.tsx
Change to a icon with some rays around a circle in the middle for the direction tag rendering.
- [Single direction (degree)](https://osmapp-git-fork-dlurak-direction-ray-osm-app-team.vercel.app/node/3023422314)
- [Single direction (letters)](https://osmapp-git-fork-dlurak-direction-ray-osm-app-team.vercel.app/node/10731370361)
- [Range](https://osmapp-git-fork-dlurak-direction-ray-osm-app-team.vercel.app/node/30131307)
- [Full 360°](https://osmapp-git-fork-dlurak-direction-ray-osm-app-team.vercel.app/node/2432753840)
> FeaturePanel: New icon for the direction tag

- src/components/FeaturePanel/PublicTransport/PublicTransport.tsx
- src/components/FeaturePanel/PublicTransport/requestRoutes.ts
The public transport categories are now more reliable by changing these things:
- Actually using routes and route_masters and not only route_master relations
- Using `highspeed=yes` tags
- Accepting both `service=high_speed` and `service=highspeed` (372 uses for the correct `high_speed` and 18 for `highspeed`)
[Frankfurt central station](https://osmapp.org/node/205364328)
| Old                                                                                       | New                                                                                       |
| ----------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------- |
| …
> FeaturePanel: Reliable public transport cateegories

- src/components/FeaturePanel/Properties/TagsTableInner.tsx
Tag groups like `payment` previously only showed the value of the first tag in the group. Most of the time it looked like this: `payment:* yes` which only shows the user that information exists but not yet any actual information.
Now `diet` and `payment` groups directly show actual information.
- [/node/9999389413](https://osmapp-ey3bct4dh-osm-app-team.vercel.app/node/9999389413)
- [/node/6632052287](https://osmapp-ey3bct4dh-osm-app-team.vercel.app/node/6632052287)
- [/node/656931109](https://osmapp-ey3bct4dh-osm-app-team.vercel.app/node/656931109)
- [/node/2351691628](https://osmapp-ey3bct4dh-osm-app-team.vercel.app/node/2351691628)
- [/node/7033879367](https://osmapp-ey3bct4dh-osm-app-team.vercel.app/node/7033879367)
> FeaturePanel: Better value for yes/no groups

- src/components/FeaturePanel/PublicTransport/LineNumber.tsx
- src/components/FeaturePanel/PublicTransport/PublicTransportWrapper.tsx
- src/components/FeaturePanel/PublicTransport/__tests__/requestRoutes.test.ts
- src/components/FeaturePanel/PublicTransport/requestRoutes.ts
Add a tooltip showing the route from the `from`, `via` and `to`tags.
> PublicTransport: Add a tooltip to public transport lines

- src/components/FeaturePanel/EditDialog/EditContent/OpeningHoursEditor/parser/__tests__/parser.test.ts
- src/components/FeaturePanel/EditDialog/EditContent/OpeningHoursEditor/parser/canItHandle.ts
https://osmapp.org/way/303646533
> OpeningHoursEditor: handle `Mo-Su 0:00-24:00` as `24/7`

- flake.lock
- flake.nix
This PR adds a `flake.nix` file. This file simplifies the on boarding process for Nix users by defining all necessary dependencies, including Node (with the correct version), Yarn and the TypeScript language server. Users can simply run `nix develop` which will drop them into a pre-configured shell ready to work on OsmAPP.
> General: Add a flake.nix file

- src/components/FeaturePanel/PublicTransport/routes/requestRoutes.ts
Introduce support for stop_areas in stop_areas.
[Amsterdam central station](https://osmapp-git-fork-dlurak-double-stopareas-osm-app-team.vercel.app/node/4290854847#14.98/52.3762/4.9015)
> Publictransport: Support stop_areas in stop_areas

- src/components/FeaturePanel/Properties/TagsTableInner.tsx
Grouping `currency:*` tags in the FeaturePanel with the yes/no preview introduced in #632 
[TD Bank in New York](https://osmapp-git-fork-dlurak-featurepane-currency-osm-app-team.vercel.app/node/2821335225)
| Old | New
| --- | --- |
| ![image](https://github.com/user-attachments/assets/200c0dbb-d92d-46dd-af53-665d57e84eb8) | ![image](https://github.com/user-attachments/assets/d37c839d-76fc-4b64-9b40-a6ee71ea5491) |
> FeaturePanel: Group `curency:*`

- src/components/SearchBox/options/preset.tsx
- src/components/SearchBox/options/stars.tsx
@zbycz noticed two more issues with the searchbox and described them [here](https://github.com/zbycz/osmapp/issues/657#issuecomment-2416618328).
This PR lowers the threshold for stars to 0.25 so they are easier to find and prefers `name` in the preset sorting.
The internal sorting and ratings for the search term "Restaurant"
> SearchBox: Lower threshold for stars and correct sorting for presets

- src/components/FeaturePanel/EditDialog/useGetHandleSave.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
When OSM API returns Response 409 or 412, osmapp stops saving without explanation.
Try to remove this Relation https://osmapp.org/relation/5250576
OSM returns 412 _Precondition failed: The relation 5250576 is used in relation 237270._
Same can be with 409 - conflict, see https://wiki.openstreetmap.org/wiki/API_v0.6#Error_codes_15
Error 404, responseText is empty:
Error 412:
Error 410:
> osmApi: Display error on save for 409/412 responses

- README.md
- flake.nix
- src/components/FeaturePanel/ImagePane/Image/InfoButton.tsx
- src/locales/de.js
- src/locales/vocabulary.js
- src/services/__tests__/osmApi.fixture.ts
- src/services/__tests__/osmApi.test.ts
- src/services/__tests__/osmToFeature.test.ts
- src/services/fetch.ts
- src/services/getCoordsFeature.ts
- src/services/images/__tests__/getBearing.test.ts
- src/services/images/__tests__/getImageDefs.test.ts
- src/services/images/__tests__/getImageFromApi.test.ts
- src/services/images/getImageDefs.ts
- src/services/images/getImageFromApi.ts
- src/services/images/getImageFromCenter.ts
- src/services/images/getImageFromCenterFactory.ts
- src/services/images/getMapillaryImage.ts
- src/services/images/getPanoramaxImage.ts
- src/services/images/getkartaViewImage.ts
- src/services/types.ts
As discussed in #517 this implements kartaview and panoramax.
The kartaview url needs to be special and doesn't go to kartaview.org but to openstreetcam; I should definitely also open a pr at the iD editor as it has this bug.
[Spicy's Gewürzmuseum, Hamburg](https://osmapp-dvhomadx0-osm-app-team.vercel.app/node/301998423#17.47/53.5427/9.9863)
> Images: Multiple sources for images from center

- src/services/images/getPanoramaxImage.ts
- src/services/images/getkartaViewImage.ts
@kudlav noticed that 360° panoramas from panoramax aren't displayed using the panellum viewer.
This fixes that for KartaView and panoramax
https://osmapp.org/node/2087588051
https://osmapp.org/node/451558193
> Images: Use panellum for panoramax and kartaview panoramas

- src/components/SearchBox/onSelectedFactory.ts
- src/components/SearchBox/options/overpass.tsx
- src/components/SearchBox/queryWizard/__tests__/queryWizard.test.ts
- src/components/SearchBox/queryWizard/ast.ts
- src/components/SearchBox/queryWizard/generateQuery.ts
- src/components/SearchBox/queryWizard/isAst.ts
- src/components/SearchBox/queryWizard/queryWizard.ts
- src/components/SearchBox/queryWizard/tokens.ts
- src/components/SearchBox/types.ts
- src/services/overpassSearch.ts
In #708 @govvin asked this:
> How do I combine this, for example: historic=* and tourism=* to find any feature having both tags?
About the overpass search option.
This lead to the idea of a overpass turbo query wizard like search.
This pull request introduces a limited version of that. Currently it only supports these:
- `and` to combine multiple things
- `or` to combine multiple things
- `key=value` for the actual key comparison, it is build in a way that other operators like `!=` are relatively easy to add
- `()` to group things combined via `and`/`or`
`(amenity=cafe or amenity=restaurant) and internet_access=yes`
`museum=art and fee=no`
`amenity=restaurant and diet:vegetarian=yes`
> Search: Query wizard like overpass searches

- src/components/FeaturePanel/EditDialog/useGetHandleSave.tsx
- src/services/osmApiAuth.ts
This fixes #714. Before uploading a changeset to osm it now checks if the in osmapp loaded version is actually the newest one. If not the upload gets blocked to prevent data loss
> EditDialog Add a version check before uploading

- src/components/FeaturePanel/helpers/StarButton.tsx
This fixes #712 
On mui there is a two year old issue where the author explains how to have pointer-events in the collapsed drawer. The star button now has `pointe-events: all` to override the inherited `pointer-events: none` from the collapsed drawer.
It is now possible to star a feature from the collapsed FeaturePanel
It can be tried on any feature
> FeaturePanel: Make the star button clickable in the collapsed FeaturePanel drawer

- src/services/getCenter.ts
- src/services/overpassSearch.ts
- src/services/types.ts
When using the overpass or preset search areas and ways were displayed as lines instead of polygons. Now they are displayed as filled polygons on the map, this makes it easier to see and click them. It is also a first step for #710
> Search: Make multipolygons and areas geojson polygons

- src/components/HomepagePanel/Homepage.tsx
This pull request includes updates to external links in the `Homepage` component to include UTM parameters for tracking purposes.
* [`src/components/HomepagePanel/Homepage.tsx`](diffhunk://#diff-13cc178133a09b0234d47cec116de1087cc29ce02cd2da36e09db718caa29004L240-R243): Updated the Vercel links to include UTM parameters for better tracking. [[1]](diffhunk://#diff-13cc178133a09b0234d47cec116de1087cc29ce02cd2da36e09db718caa29004L240-R243) [[2]](diffhunk://#diff-13cc178133a09b0234d47cec116de1087cc29ce02cd2da36e09db718caa29004L250-R256)
> general: correct link to vercel on Homepage.tsx

- public/sockets/schuko.svg
- public/sockets/type1.svg
- public/sockets/type2.svg
- public/sockets/unknown.svg
- src/components/FeaturePanel/FeaturePanel.tsx
- src/components/FeaturePanel/Sockets/README.md
- src/components/FeaturePanel/Sockets/Socket.tsx
- src/components/FeaturePanel/Sockets/Sockets.tsx
- src/components/FeaturePanel/Sockets/img.ts
- src/components/FeaturePanel/Sockets/useSocketTags.tsx
As proposed in #732 I've added some boxes for the `socket:*` tags.
I've created the vector graphics myself. When no specific graphic is available it fallsback to a generic one which features a question mark, in this case it is reported to sentry so we can see which socket types need to get custom graphics.
[Tesla Supercharger (No image yet)](https://osmapp-git-fork-dlurak-sockets-osm-app-team.vercel.app/node/11902579098)
[Tesla destination and type 1 charger (No images yet)](https://osmapp-git-fork-dlurak-sockets-osm-app-team.vercel.app/node/10137915436)
[Schuko and type 2](https://osmapp-git-fork-dlurak-sockets-osm-app-team.vercel.app/node/5112637663)
Maybe also one for ChaDeMo
> FeaturePanel: Add a socket:* view

- src/components/Directions/DirectionsAutocomplete.tsx
- src/components/Directions/DirectionsForm.tsx
- src/components/Directions/Instructions.tsx
- src/components/Directions/Result.tsx
- src/components/Directions/TextMarker.tsx
- src/components/SearchBox/options/coords.tsx
> Directions: Add marker on map + improve instruction panel

- src/components/LayerSwitcher/LayerSwitcherContent.tsx
- src/components/LayerSwitcher/osmappLayers.tsx
- src/components/Map/behaviour/useUpdateStyle.tsx
- src/components/Map/consts.ts
Lets evaluate how it works. If it needs any updates to style etc.
Added as separate layer in LayerSwitcher:
Issue:
#693
> Map: add OpenFreeMap provider

- next.config.mjs
- sentry.client.config.ts
We were hitting 80 GB-Hrs out of 100 in our hobby plan recently.
I would like to test if sentry tunnelRoute helps this or not. Also i didn't find replays particulary useful, maybe we can make do without them.
Lets evaluate it in a month or so.
----
We have heavy usage from old URLs of our logos: 🤔
> general: experiment - disable sentry tunnelRoute

- src/components/FeaturePanel/Climbing/ConvertedRouteDifficultyBadge.tsx
- src/components/FeaturePanel/Climbing/utils/grades/routeGrade.ts
> Climbing grades: Support approximation symbol

- src/components/SearchBox/onSelectedFactory.ts
- src/components/SearchBox/options/overpass.tsx
- src/components/SearchBox/types.ts
Every AST search was adding nulls which looked like this:
> SearchBox: fix `null`s in overpass history

- .env
- .gitignore
- src/components/Directions/routing/getGraphhopperResults.ts
- src/components/LayerSwitcher/osmappLayers.tsx
- src/components/Map/BrowserMap.tsx
- src/components/Map/behaviour/useUpdateStyle.tsx
- src/components/Map/consts.ts
- src/components/Map/styles/rasterStyle.ts
- src/components/utils/MapStateContext.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
- add transport layer by [thunderforest.com](https://thunderforest.com)
- switch to dark version, when user theme changes (added support for `darkUrl` for raster layers and overlays)
Also fixes #604
> Map: add transport layer + dark mode

- .gitignore
- package.json
- src/components/LayerSwitcher/osmappLayers.tsx
- src/components/Map/MapFooter/AttributionLinks.tsx
- src/components/Map/behaviour/indoor.tsx
- src/components/Map/behaviour/useOnMapClicked.tsx
- src/components/Map/behaviour/useUpdateStyle.tsx
- src/components/Map/useAddTopRightControls.tsx
- src/components/utils/MapStateContext.tsx
- src/helpers/GlobalStyle.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
- yarn.lock
DEMO: https://osmapp-git-indoor-osm-app-team.vercel.app/
Proof of concept for Indoor tiles 🎉 - aka #225
Thanks [contrapunctus](https://www.openstreetmap.org/user/contrapunctus) for heads up about indoorequal service. And @francois2metz for creating it ofc! 😃👍 
More links:
- https://github.com/indoorequal/maplibre-gl-indoorequal
- https://indoorequal.org/#map=18.28/50.083387/14.433989&level=-3
- https://status.indoorequal.org/
TODO
> Map: add indoor tiles by indoorequal.com

- src/components/FeaturePanel/Climbing/ClimbingTypeBadge.tsx
- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
> ClimbingView: Add boulder badge to crag and route detail

- src/components/HomepagePanel/UserSettingsDialog.tsx
- src/locales/de.js
- src/locales/vocabulary.js
The changes in #731 made it very easy to fix #572 and add a metric/imperial switch to the user settings
> Settings: Add metric/imperial switch

- .env
- pages/_document.tsx
- src/components/App/helpers.ts
- src/server/logRequest.tsx
- src/services/fetch.ts
- src/services/intl.tsx
- src/services/intlServer.tsx
On some days we have 100k of page loads of Vercel Serveless Function. Currently we had to switch to payed Pro plan from the Hobby.
We need to debug where this traffic comes from to be able to optimize it.
> general: log server load events to tweak vercel bill

- package.json
- src/components/Map/behaviour/useInitMap.tsx
- yarn.lock
> maplibre: Add globe projection

- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/ClimbingViewContent.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/utils/UserSettingsContext.tsx
> Climbing: Persist splitPaneSize in UserSettingsContext

- src/components/FeaturePanel/EditDialog/EditContent/ContributionInfoBox.tsx
- src/components/FeaturePanel/EditDialog/EditContent/EditContent.tsx
- src/components/FeaturePanel/EditDialog/EditDialog.tsx
- src/components/FeaturePanel/EditDialog/EditDialogTitle.tsx
- src/locales/vocabulary.js
1 entity
2 entities
3 entities + mobile resolution
cc @zbycz
> Style multi edit dialog

- src/components/Directions/DirectionsAutocomplete.tsx
- src/components/Directions/DirectionsBox.tsx
- src/components/Directions/DirectionsContext.tsx
- src/components/Directions/DirectionsForm.tsx
- src/components/Directions/ModeToggler.tsx
- src/components/Directions/Result.tsx
- src/components/Directions/useGetOnSubmit.tsx
- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
- src/components/FeaturePanel/Climbing/utils/array.ts
- src/components/SearchBox/renderOptionFactory.tsx
- src/helpers/GlobalStyle.tsx
> Directions: Move from/to to array of points

- src/components/Directions/DirectionsAutocomplete.tsx
- src/components/Directions/DirectionsForm.tsx
- src/components/Directions/helpers.tsx
- src/components/Directions/routing/getGraphhopperResults.ts
- src/components/Directions/useGetOnSubmit.tsx
- src/locales/vocabulary.js
> Direction: Add another destination

- src/components/SearchBox/queryWizard/__tests__/queryWizard.test.ts
- src/components/SearchBox/queryWizard/ast.ts
- src/components/SearchBox/queryWizard/generateQuery.ts
- src/components/SearchBox/queryWizard/isAst.ts
- src/components/SearchBox/queryWizard/queryWizard.ts
- src/components/SearchBox/queryWizard/tokens.ts
As described in #849 this adds a `!=` operator to the query wizard.
> SearchBox: Add a `!=` operator to the query wizard

- src/components/FeaturePanel/PublicTransport/routes/Routes.tsx
- src/components/FeaturePanel/PublicTransport/routes/useShowOnMap.ts
If a train station has only categories that are not shown by default the map didn't include a single route. Even worse when the train station has only one category of type (for example only "unknown" or only "high speed" as it is the case in "Limburg Süd") it isn't even possible to turn the categories on. Now at least one category is shown all of the time
[Limburg Süd](https://osmapp.org/node/4530820013)
> PublicTransport: Fix a bug with default categories

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/TagsEditor/KeyInput.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/TagsEditor/ValueInput.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/TagsEditor/helpers.tsx
This is replacement for MUI's TextField,
it was rendering 4 seconds for 200 tags.
http://127.0.0.1:3000/node/1601837931
> EditDialog: optimize performace of TagsEditor

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/TagsEditor/KeyInput.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/TagsEditor/TagsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/TagsEditor/helpers.tsx
User can add more rows, and then fill them out. Empty keys are already filtered out on authOsmApi level.
> EditDialog: enable adding more rows in TagsEditor

- src/services/images/getCommonsImageUrl.ts
support for following:
- `File:Seidelbruch - Bruchwächter - Südwest.jpg` (worked before)
- `https://commons.wikimedia.org/wiki/File:Seidelbruch_-_Bruchw%C3%A4chter_-_S%C3%BCdwest.jpg` (new)
- `File:Seidelbruch_-_Bruchw%C3%A4chter_-_S%C3%BCdwest.jpg` (new)
> Gallery: Support different URL variants on wikimedia commons

- .env
- pages/api/user.ts
- src/components/utils/OsmAuthContext.tsx
- src/services/osmApi.ts
- src/services/osmApiAuth.ts
- src/services/osmApiConsts.ts
You can prepare test items in iD editor here:
https://master.apis.dev.openstreetmap.org/edit
To use TEST API add `NEXT_PUBLIC_ENABLE_TEST_API=true` to your `.env.local`.
> osmApi: switch to TEST API via .env

- src/components/FeaturePanel/EditDialog/EditContent/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/useEditItems.tsx
- src/services/getCoordsFeature.ts
- src/services/helpers.ts
- src/services/osmApi.ts
- src/services/osmApiAuth.ts
- src/services/types.ts
Works only for relations which `hasAtLeastOneNode`. The location is moved 10m from the last point.
In future there will be a location on map.
On test api:
https://master.apis.dev.openstreetmap.org/relation/4305224335
> EditDialog: add new member to relation

- src/components/FeaturePanel/EditDialog/EditContent/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/EditContent.tsx
- src/components/FeaturePanel/EditDialog/useEditItems.tsx
- src/components/FeaturePanel/EditDialog/useGetHandleSave.tsx
- src/components/FeaturePanel/FeatureDescription.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
- src/components/FeaturePanel/OsmError.tsx
- src/components/FeaturePanel/helpers/TestApiWarning.tsx
- src/services/osmApiAuth.ts
- rename `newNodeLonLat` to `nodeLonLat`
- fill this value for any node added to editItems (new or existing)
- add xml for existing item
Also:
- add TestApi Warning
- change Website urls to currently used instance
> osmApi: implement `nodeLonLat` for existing node

- src/components/utils/TooltipButton.tsx
When hovering over TooltipButton user should be able to click on links inside the tooltip. This was broken after upgrade on latest MUI.
Mobile behaviour unaffected.
> general: fix TooltipButton to stay open on desktop

- src/components/FeaturePanel/Climbing/CragMap.tsx
- src/components/FeaturePanel/EditDialog/EditContent/EditContent.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/EditFeatureMap.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/FeatureEditSection.tsx
- src/components/FeaturePanel/EditDialog/EditContent/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ParentsEditor.tsx
- src/components/FeaturePanel/MemberFeatures/MemberFeatures.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> EditDialog: Add map

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/PresetSearchBox.tsx
> EditDialog: Show climbing presets as default in openclimbing

- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
Sentry still sends some requests on localhost even though `enabled: false` 😅.. lets take the DSN from it, so it really can't send anything.
> general: turn off sentry - really

- src/components/FeaturePanel/EditDialog/EditContent/EditContent.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/EditFeatureMap/EditFeatureMap.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/PresetSearchBox.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/PresetSelect.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureRow.tsx
- src/components/FeaturePanel/EditDialog/EditContent/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ParentsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/helpers.tsx
- src/components/FeaturePanel/EditDialog/EditDialog.tsx
- src/components/FeaturePanel/EditDialog/EditDialogTitle.tsx
- src/components/HomepagePanel/HomepageOpenClimbing.tsx
- src/components/HomepagePanel/HomepageOpenClimbingGallery.tsx
> EditDialog: Improve tabs

- src/components/FeaturePanel/FeatureDescription.tsx
- src/components/FeaturePanel/FeatureHeading.tsx
> FeaturePanel: Polish feature header

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/LocationEditor/LocationEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ParentsEditor.tsx
- src/services/osm/fetchWays.ts
- src/services/osm/urls.ts
When node is inside a way, we show warning instead of the Map:
> EditDialog: add LocationEditor node-in-way check

- src/server/climbing-tiles/refreshClimbingTiles.ts
With `._` we have on preview:
```
Starting...
Overpass elements: 201367
Records: 41737
SQL Query length: 14531069 chars
Done.
Duration: 84808 ms
```
> climbingTiles: add missing routes

- src/services/__tests__/osmApi.fixture.ts
- src/services/getCoordsFeature.ts
- src/services/images/__tests__/getImageDefs.test.ts
- src/services/images/getImageDefs.ts
- src/services/osm/osmApi.ts
- src/services/osm/osmToFeature.ts
It doesn't make sense to show street-level imagery for relations, because their `center` point is just computed as centroid of all its members - so it can be very far from any actual stuff in the relation.
This is open for discussion – if anyone finds any actual usecase, I am open to revert this PR :-)
> images: remove street-view images for relations

- src/components/FeaturePanel/CragsInArea.tsx
eg https://openclimbing.org/relation/14222914
> climbing: add other list below CragsInArea

- pages/api/climbing-tiles/stats.ts
- pages/api/climbing-tiles/tile.ts
- src/components/LayerSwitcher/Overlays.tsx
- src/components/utils/TooltipButton.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
- src/server/climbing-tiles/db.sql
- src/server/climbing-tiles/db.ts
- src/server/climbing-tiles/getClimbingStats.ts
- src/server/climbing-tiles/getClimbingTile.ts
- src/server/climbing-tiles/overpass/overpassToGeojsons.ts
- src/server/climbing-tiles/refreshClimbingTiles.ts
- src/server/climbing-tiles/utils.ts
- src/types.ts
Add API endpoint `api/climbing-tiles/stats`, which shows statistics about last ClimbingTiles refresh and some useful numbers:
eg.
```
{
"lastRefresh": "2025-02-11T06:29:30.892Z",
"osmDataTimestamp": "2025-02-11T06:26:33Z",
"devStats": {
"id": 1,
"build_duration": "91728",
"max_size": "284394",
"max_size_zxy": "6/34/21",
"max_time": "1219",
"max_time_zxy": "6/34/21"
},
"groupsCount": 15970,
"groupsWithNameCount": 14878,
"routesCount": 19421
}
```
In LayerSwitcher we show the timestamp of the data:
- NA server-side-rendering (SSR)
> climbingTiles: add stats

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/PresetSearchBox.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> PresetSearchBox: Add warning and different cursor

- src/components/Directions/Result.tsx
- src/components/LayerSwitcher/AddCustomLayer.tsx
- src/components/LayerSwitcher/BaseLayers.tsx
- src/components/LayerSwitcher/Overlays.tsx
- src/components/LayerSwitcher/osmappLayers.tsx
- src/components/utils/MapStateContext.tsx
- src/components/utils/TooltipButton.tsx
> LayerSwitcher: add secondLine for some layers

- src/services/__tests__/fetchCrags.test.ts
- src/services/__tests__/overpassAroundToSkeletons.test.ts
- src/services/__tests__/overpassSearch.test.ts
- src/services/getPoiClass.ts
Closed: #966
User marker icon
Search for hydrants
> Icons: Use marker icon instead of information for generic POIs

- src/components/FeaturePanel/QuickActions/ShareDialog/useGetItems.ts
Relation can have no `center`, when Overpass is broken, or it is new item that was not yet imported to overpass. Via #970
Then it will look like this:
> FeaturePanel: fix ShareDialog when no center

- src/components/Directions/DirectionsAutocomplete.tsx
- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/options/geocoder.tsx
- src/components/SearchBox/options/overpass.tsx
- src/components/SearchBox/useGetOnSelected.ts
- src/components/SearchBox/useGetOptions.tsx
- src/components/SearchBox/useHandleDirectQuery.tsx
Based on PR #988 by @amenk.
You can supply eg a query `?qd=London` and osmapp will open as if user typed this query and selected first result.
Sometimes it can be confusing, because Preset category is first matching result. But you can easily click the SearchBox and select the second result.
Note: photon geocoder is experiencing long loading times, maybe becuase the company got acquired recently.
TODO add opensearch.xml
TODO show spinner while loading the result
> SearchBox: implement ?qd=query for search from browser

- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/SearchBox.tsx
- src/components/SearchBox/useHandleDirectQuery.tsx
Circular spinner while geocoder may be loading - the same spinner which runs for overpass when onSelected is called.
> SearchBox: add spinner for `?qd=query`

- pages/_app.tsx
- pages/api/climbing-tiles/stats.ts
- pages/api/climbing-tiles/tile.ts
- pages/api/og-image.tsx
CDN will cache all SSR requests for 1 hour. Unfortunately this means, that user can click inside OsmAPP, then hit ctrl+R and receive older data. But 1 hour is not that painful.
Lets see if this dramatically lowers the number of SSR execution. We still have around 10k per day, which is better but lets see.
It would be cool to see which URLs are being served, and if this is caused by accessing one URL many times in one day, but this costs another 20€/monthly on vercel, which is too much for our small project. :)
// update: every feature unfortunately sends a set-cookie which prevents the caching. Hmm?
> general: add Cache-control headers

- src/components/FeaturePanel/EditDialog/useEditItems.tsx
- src/components/FeaturePanel/helpers/TestApiWarning.tsx
- src/services/osm/auth/__tests__/getDiffXml.test.ts
- src/services/osm/auth/__tests__/getFirstId.test.ts
- src/services/osm/auth/api.ts
- src/services/osm/auth/getDIffXml.ts
- src/services/osm/auth/xmlHelpers.ts
- src/services/osm/auth/xmlTypes.ts
- src/services/osm/getFirstId.ts
- src/services/osm/osmApiAuth.ts
This updates the way OsmAPP saves changes to OSM. Until now, we saved each node/way/relation in separate request as GET/PUT/POST. From this PR we send the osmChange diff (.xml.osc). 
This makes possible to delete old node and convert it to relation - https://github.com/zbycz/osmapp/pull/954. In this process we want to change the "deleted node id" in all parent relations to the new relation id instead. But without diff we were updating the parent relation refs to a not-yet-created relation. 
In future we would also be able to offer download of OSC file to edit it in different OSM editor.
> osmApi: change to .osc diff upload

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ItemHeading.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ItemsTabs.tsx
- src/components/FeaturePanel/EditDialog/EditDialog.tsx
- src/components/FeaturePanel/EditDialog/useEditItems.tsx
In this process we want to change the "deleted node id" in all parent relations to the new relation id instead.
Also:
- before showing the EditDialog - we refresh the item (to ensure we have memberFeatures)
- when adding node and we have no previous in relation, we use the MapView
Followup:
- when using the mapview - we need to show a warning (or prompt the user to confirm it)
- when deleting a node, we want to forbid any edits, as OsmApi probably needs exactly the last version.
> osmApi: convertToRelation - deletes existing node

- pages/_app.tsx
- pages/api/climbing-tiles/stats.ts
- pages/api/climbing-tiles/tile.ts
- pages/api/og-image.tsx
No improvement in number of exections. 
It doesnt work much thanks to:
- pages are using set-cookie = no CDN cache
- climbing-tiles sets CORS based on origin = wrong CDN cache
> Revert "general: add Cache-control headers (#1004)"

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MajorKeysEditor.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> EditDialog: Add simple validation for upload photo

- src/components/FeaturePanel/FeatureImages/Image/InfoButton.tsx
- src/components/FeaturePanel/FeatureImages/useLoadImages.tsx
- src/components/Map/MapFooter/AttributionLinks.tsx
Previously we filtered out duplicate images with the exact same url.
But it is possible that the wikimedia and wikipedia image show the same image but with a different resolution (e.g. 500 and 410px). 
This pr now also filters out such duplicates and only shows the image with the higher resolution
[Frankfurt Central Station](https://osmapp-git-fork-dlurak-wikimedia-duplicates-osm-app-team.vercel.app/node/205364328)
> Images: No duplicate wikimedia images

- src/components/FeaturePanel/QuickActions/ShareDialog/items.ts
- src/components/FeaturePanel/QuickActions/ShareDialog/useGetItems.ts
- src/components/FeaturePanel/helpers/externalLinks.ts
- src/components/LayerSwitcher/AddLayerButton.tsx
- src/components/LayerSwitcher/osmappLayers.tsx
- src/components/utils/MapStateContext.tsx
The share dialog allows for opening a feature in many other map providers, previously apple maps already was opened with the normal/satellite layer depending on the currently active layer in osmapp.
The detection whether a layer is a satellite layer now also supports user layers.
Google-Maps now also opens with the appropiate layer, allthough it isn't possible to force google maps from satellite to roadmap :(
> ShareDialog: Open external maps with appropiate layer

- package.json
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/helpers.tsx
- src/components/FeaturePanel/EditDialog/EditContext.tsx
- src/components/FeaturePanel/EditDialog/EditDialog.tsx
- src/components/FeaturePanel/EditDialog/__tests__/useEditItems.test.tsx
- src/components/FeaturePanel/EditDialog/itemsHelpers.ts
- src/components/FeaturePanel/EditDialog/useEditItems.tsx
- src/services/helpers.ts
- src/services/osm/getFullFeatureWithMemberFeatures.ts
- src/services/osm/helpers.ts
- src/services/osm/osmApi.ts
- yarn.lock
Bigger refactoring of the EditDialog "backend". There were several issues with using Feature in EditDialog:
- multiple conversion - from `OsmElement` -> `Feature` -> `DataItem`  
- some meaning was lost in the process, which made the code less readable and prone to future errors
- e.g. we had to use `center` for reading the nodeLonLat - eventhough this was correct only for node
- for EditDialog we want fresh data, but Feature could have been older, potentially cached. 
- for EditDialog we need to fetch eg. all nodes for ways, which is not useful to have in FeaturePanel (SSR needs to serialize it and this could make the payload too big)
- for EditDialog we always need the FullFeature (with all member features) to see better label of members (name or preset name), but the FeaturePanel …
> EditDialog: refactor EditContext to work with DataItem not Feature

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ConvertNodeToRelation.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/PresetSearchBox.tsx
- src/components/FeaturePanel/EditDialog/EditContent/useHandleItemClick.tsx
- src/components/FeaturePanel/EditDialog/EditContext.tsx
- src/components/FeaturePanel/EditDialog/__tests__/useEditItems.test.tsx
- src/components/FeaturePanel/EditDialog/useEditItems.tsx
- src/services/osm/auth/getDIffXml.ts
We can safely remove a node from items, if it was a new one.
> EditDialog: remove "new" node converted to relation

- src/components/Map/consts.ts
- src/components/Map/styles/outdoorStyle.ts
New tiles have better granularity for countours and hillshading, and also they are discontinuing the old tiles this year.
Update to outdoor-v2 *style* is in #444.
|old|new|
|--|--|
| ![Screenshot 2025-05-11 at 13 14 11](https://github.com/user-attachments/assets/55d35c3b-ce9a-4d76-bd7e-f7adebd8815e) | ![Screenshot 2025-05-11 at 13 14 15](https://github.com/user-attachments/assets/b5e24003-5595-4fe8-b01f-838e34417731) |
> Map: use maptiler outdoor-v2 tiles

- src/components/FeaturePanel/Climbing/ClimbingViewContent.tsx
- src/components/FeaturePanel/Climbing/RouteDistribution.tsx
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
- src/utils.ts
+ refactor RouteDistribution to load it from features, not climbing context
> RouteDistribution: Add distribution also for climbing areas

- src/components/FeaturePanel/EditDialog/EditContent/ItemsTabs.tsx
> EditDialog: fix missing TabName + add NwrIcon

- src/services/__tests__/osmApi.fixture.ts
- src/services/osm/osmToFeature.ts
- src/services/types.ts
It is not needed anymore, as EditDialog fetches its own "full" featues, and stores `nodes` in `DataItems`.
> osmApi: remove `nodes` for ways

- .eslintrc.json
- eslint-local-rules.js
- package.json
- yarn.lock
Correct:
```
const Wrapper = styled(Stack, {
shouldForwardProp: (prop) => !prop.startsWith('$'),
})<{ $isMobileMode: boolean }>`
```
https://typescript-eslint.io/play/#ts=5.8.2&showAST=es&fileType=.ts&code=MYewdgzgLgBA6gJwIYAcUFMEwLw2gTwBt0ATEgCgGUolgBrAShgB4BvGAEgEsIBZEAEZdi-EugBcMASBDEkYGAF8AfAAMAUDBgoQELlC7hJSARFkBXKOgDc61baA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false
> general: add eslint rule for transient props

- src/services/images/__tests__/getImageDefs.test.ts
- src/services/images/getImageDefs.ts
node/5064026138
way/75585401
| 1 | 2 |
|--|--|
| ![image](https://github.com/user-attachments/assets/48256229-6087-4748-b2f4-744b0461f25a) |![image](https://github.com/user-attachments/assets/0b78f09c-faa8-471d-8413-652c5a44d742) |
> images: strip nonsense `image*=*` tags

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/LocationEditor/useStaticMarkers.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ParentsEditor.tsx
- src/components/FeaturePanel/EditDialog/itemsHelpers.ts
We need typescript strict mode #571, this could have been caught statically.
> EditDialog: fix osmElement.tags may be undefined

- .env
- src/components/App/google-analytics.tsx
- src/components/App/umami.tsx
- src/services/osm/consts.ts
> general: Move telemetry website IDs to env (Umami, GTM) as well as OSM Test server

- src/components/FeaturePanel/Climbing/config.ts
> Climbing: Add route line scaling according to image width

- src/components/FeaturePanel/Climbing/Editor/RoutesEditor.tsx
> Climbing: Fix wikimedia_commons encoded URI path

- .env
- src/components/App/umami.tsx
It was introduced to mitigate the large cost of vercel executions. It is no longer needed.
> general: remove Umami for osmapp.org

- pages/api/climbing-tiles/stats.ts
- pages/api/climbing-tiles/tile.ts
- src/components/Map/climbingTiles/__tests__/computeTiles.test.ts
- src/components/Map/climbingTiles/computeTiles.ts
- src/locales/cs.js
- src/locales/vocabulary.js
- src/server/climbing-tiles/__tests__/utils.test.ts
- src/server/climbing-tiles/addCorsAndCache.ts
- src/server/climbing-tiles/utils.ts
- vercel.json
Cache is set for 1 hour, so after the refresh 3:00 AM UTC, it may still give old results until 4:00 AM UTC.
Also `stale-while-revalidate: until next refresh` used to speed up the data recovery during the day. In theory, it should give the old data until refresh is run, and in background fetch data from backend. This could be useful if we ever want to refresh the data during the day again.
Wildcard is needed to enable the vercel cache, it ignores the `origin` and caches randomnly one
> climbingTiles: set vercel cache + cors wildcard

- src/components/FeaturePanel/FeatureImages/Image/InfoButton.tsx
- src/locales/de.js
- src/locales/vocabulary.js
- src/services/images/__tests__/getImageFromApi.test.ts
- src/services/images/getImageFromCenterFactory.ts
- src/services/images/getPanoramaxImage.ts
In #1116 @atchisson informed us that panoramax images can implement the license they want and that osmapp should show that license.
> Images: Show the panoramax license

- pages/api/load-og-image.tsx
- src/components/FeaturePanel/renderers/WebsiteRenderer.tsx
- src/components/FeaturePanel/renderers/helpers.ts
- src/locales/de.js
- src/locales/vocabulary.js
- src/services/images/__tests__/getImageDefs.test.ts
- src/services/images/getImageDefs.ts
- src/services/images/getImageFromApi.ts
There is a very old idea to fetch the og:image (see #132) from websites which provide one. Here I've implemented it.
https://osmapp-git-fork-dlurak-external-og-image-osm-app-team.vercel.app/node/11243721137
https://osmapp-git-fork-dlurak-external-og-image-osm-app-team.vercel.app/node/313822575
> Images: Load og-image for features

- src/components/FeaturePanel/Properties/__tests__/interval.test.ts
- src/components/FeaturePanel/Properties/interval.ts
- src/components/FeaturePanel/Properties/renderTag.tsx
There are many different formats for the interval tag on osm: https://wiki.openstreetmap.org/wiki/Key:interval
And sometimes it is mapped wrong, like `120` instead of `02:00`, or `168:00` (once every week)
Tries to always show the interval in either `HH:MM` or when needed `HH:MM:SS`
`interval=*`
> FeaturePanel: Show intervals always as `HH:MM` or when needed as `HH:MM:SS`

- src/components/FeaturePanel/helpers/color.ts
The `colour` tag and public transport is shown colorfull. Up until this PR we supported hex colors and the 16 basic css colors. This PR introduces support for all css colors
- **Previously unsupported:** `colour=brown or colour=beige` 
- **Hex is still supported:** `op:nwr["colour"~"#[0-9a-fA-F]{6}"]`
- ***Basic* CSS-colors are still supported:** `colour=red or colour=navy`
> general: Allow all css colors

- src/server/climbing-tiles/refreshClimbingTiles.ts
For some reason, we got out of memory even on 1.8 MB queries:
> climbingTiles: make insert SQLs smaller

- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
All routes are rendered with `key={routeNumber}`
and then as override comes `selectedRoute` and `hoveredRoute`. Both doesn't have to be array, as only one can be selected/hovered.
> climbing: refactor - add react key to RoutesLayer

- src/components/FeaturePanel/Climbing/Editor/Points/Anchor.tsx
- src/components/FeaturePanel/Climbing/Editor/Points/Bolt.tsx
- src/components/FeaturePanel/Climbing/Editor/Points/Piton.tsx
- src/components/FeaturePanel/Climbing/Editor/Points/Point.tsx
- src/components/FeaturePanel/Climbing/Editor/Points/Sling.tsx
- src/components/FeaturePanel/Climbing/Editor/Points/UnfinishedPoint.tsx
- src/components/FeaturePanel/Climbing/Editor/Points/pointTypes.ts
- src/components/FeaturePanel/Climbing/Editor/RouteMarks.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteWithLabel.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
- src/components/FeaturePanel/Climbing/Editor/StartPoint.tsx
- src/components/FeaturePanel/Climbing/Editor/utils.tsx
I moved the handler to the most bottom component, which had some useClimbingContext connection.
That allowed to remove of passing the onclick prop through many layers.
> climbing: refactor - extract onPointClick() to utils

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ParentsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/useHandleItemClick.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> EditDialog: Add open all for members/parents

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MajorKeysEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/WikimediaCommonsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/helpers.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> EditDialog: Update helper texts for desc and photos

- src/components/FeaturePanel/Climbing/Editor/PathWithBorder.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutePath.tsx
This fixes a bug, where route was not properly clickable - when its svg path was over another's route interactive areas.
> climbing: refactor - svg path always pointer-events:none

- src/components/FeaturePanel/Climbing/Editor/MouseTrackingLine.tsx
- src/components/FeaturePanel/Climbing/Editor/Points/Point.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteMarks.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutePath.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteWithLabel.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
- src/components/FeaturePanel/Climbing/Editor/StartPoint.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
routeNumber is the route index, renamed to avoid the confusion.
This enabled RoutesLayer to get much shorter, as we don't have to ask if every routeNumber isSelected() and isHovered().
> climbing: refactor - rename to use `routeIndex`

- src/components/FeaturePanel/Climbing/Editor/RouteNumber.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteWithLabel.tsx
- src/components/FeaturePanel/Climbing/Editor/StartPoint.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
This code was doubled for StartPoint and RouteWithLabel. Now it lives only in `<RouteNumber/>`
> climbing: refactor - make RouteNumber consume only 'routeIndex'

- src/components/FeaturePanel/Climbing/Editor/MouseTrackingLine.tsx
- src/components/FeaturePanel/Climbing/Editor/PathWithBorder.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutePath.tsx
`d` is left for later
Reducing unneeded props - increasing readabilty.
> climbing: refactor - make PathWithBorder consume only routeIndex+d

- src/components/FeaturePanel/Climbing/Editor/InteractivePath.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
There was missing `.current` in:
```
if (!isPanningActiveRef.current) {
machine.execute('cancelRouteSelection');
}
```
> climbing: fix click in canvas to deselect route

- src/components/FeaturePanel/Climbing/Editor/InteractivePath.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
Midpoint shown only on the "hover" instance, but works when clicked also on any instance.
> climbing: fix multiple midpoints

- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/FeaturePanel/Climbing/utils/useGetMachineFactory.ts
Maximum value of an OSM key is 255 chars.
One point is 13 chars `0.123,0.123B|`, 255/13 = 19.6. So we use the maximum of 19 points.
> climbing: check maximum number of points

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/PresetSelect/useOptions.tsx
- src/components/FeaturePanel/EditDialog/useEditItems.tsx
- src/services/tagging/ourPresets.ts
When creating new crag (as a node) and converting it to relation - it was losing the node clicked location. Fixed.
Also added `type/site/climbing/area` to default presets.
> EditDialog: fix convertToRelation to use clicked position

- src/components/Map/climbingTiles/climbingTilesSource.ts
- src/server/climbing-tiles/buildTileGeojson.ts
- src/types.ts
use the `name` - it should be cached everywhere now, via #1309
> climbingTiles: fix skeleton to show name - part 2

- src/server/climbing-tiles/refreshClimbingTiles.ts
Neon dosn't have such strange memory limits as xata lite, so we can send 2MB queries which is 1.5x faster
> climbingTiles: larger queries to speed up refresh

- src/components/Map/climbingTiles/climbingLayers/groupsLayer.ts
- src/components/Map/climbingTiles/climbingLayers/routesLines.ts
- src/components/Map/climbingTiles/climbingLayers/routesPoints.ts
- src/server/climbing-tiles/overpass/overpassToGeojsons.ts
Was 0 - now shows num of crags, which also gives priority to display:
Was
now without points:
> climbingTiles: area default to # of crags + fix points

- pages/api/climbing-ticks/[id].ts
- pages/api/climbing-ticks/index.ts
- pages/api/climbing-tiles/refresh.ts
- src/server/climbing-tiles/db.ts
- src/server/climbing-tiles/getClimbingSearch.ts
- src/server/climbing-tiles/getClimbingStats.ts
- src/server/climbing-tiles/getClimbingTile.ts
- src/server/climbing-tiles/refreshClimbingTiles.ts
Unfortunately, i havent noticed, that NeonDB free plan comes only with 50 hours of compute time per month. And each time DB is woke up, it stays 5 minutes up (usually idling).
It is 14th day of month, and we have already spent 42hours. 
XATA is very slow and accessibile only with restQueries (there is no connection pooler like pgBouncer), but we were happy with it since February.
> climbingTiles: revert back from neon to xata

- src/components/Map/climbingTiles/climbingTilesSource.ts
- src/components/utils/userSettings/getClimbingFilter.tsx
Switching of layers is possible even without the mapdiff (#1113)
Condition was wrong - always performing the updateData even though no filter changed.
> climbingTiles: show on styledata + fix filter condition

- src/components/Map/climbingTiles/climbingTilesSource.ts
- src/components/utils/userSettings/getClimbingFilter.tsx
- src/server/climbing-tiles/buildTileGeojson.ts
- src/server/climbing-tiles/db.sql
- src/server/climbing-tiles/db.ts
- src/server/climbing-tiles/refreshClimbingTilesHelpers.ts
- src/types.ts
For route we return gradeTxt field, which is used as fallback when no gradeSystem is selected. Otherwise we use gradeId (already present for filtering).
Also refactoring of getProperties()
> climbingTiles: convert grades on map

- src/components/FeaturePanel/EditDialog/EditContent/FeatureRow.tsx
- src/components/FeaturePanel/EditDialog/context/utils.ts
- src/locales/cs.js
- src/locales/vocabulary.js
The preset is already computed for opened `items`, lets use it as an icon.
> EditDialog: show icon for members in `items`

- src/components/FeaturePanel/EditDialog/EditContent/ItemsTabs.tsx
Otherwise it was jumpy after opening items with longer label.
eg. relation/17424001
> EditDialog: set default width for ItemsTabs

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MajorKeysEditor.tsx
It is already written in the climbing section - with action button - #1340.
> EditDialog: remove helper text for `description`

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MajorKeysEditor.tsx
Mistake - should have been the wikimedia_commons helper.
> Revert "EditDialog: remove helper text for `description` (#1392)"

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/WikimediaCommonsEditor.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
- src/locales/zh-CN.js
- src/locales/zh-HK.js
- src/locales/zh-TW.js
It is already written in the climbing section - with action button - #1340.
> EditDialog: remove helper text for `wikimedia_commons`

- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
- src/components/FeaturePanel/Climbing/Ticks/MyRouteTicks.tsx
The initial request for /api/climbing-ticks (get all) is only enabled for PROJECT_ID===openclimbing. 
The addTick buttons should be disabled, because it never load the actual ticks.
> ClimbingTicks: hide it on non-climbing project

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/AutocompleteSelect.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ClimbingRockSelect.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/GradeSelect.tsx
- autocomplete is controlled
- fix climbing rock material select
- fix grade system select
> Climbing: Fix autocomplete issues

- src/components/FeaturePanel/EditDialog/EditContent/EditDialogActions.tsx
- src/components/FeaturePanel/EditDialog/EditDialog.tsx
- src/components/FeaturePanel/EditDialog/utils.ts
> EditDialog: Add confirm on Editdialog close

- src/components/FeaturePanel/Climbing/GradeSystemSelect.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ClimbingEditor/ClimbingGradesEditor.tsx
Also - user always has to see the option to select "no value", because it influences the whole app. ==> removed `allowUnsetValue`.
> climbing: GradeSystemSelect - showDefaultOnButton

- src/components/FeaturePanel/CragsInArea.tsx
The filtering button was hiding when filter got 0 or 1 results. Preventing the user to "unfilter" again.
Fixed.
> CragsInArea: don't ever hide the filtering button

- src/components/HomepagePanel/UserSettingsDialog.tsx
- src/components/Map/climbingTiles/climbingLayers/outlinesLayer.ts
> climbingTiles: add dev user-setting to show all outlines

- src/components/Map/climbingTiles/climbingLayers/groupsLayer.ts
Much better! :D
| 1 | 2 |
|--|--|
|<img width="433" height="351" alt="image" src="https://github.com/user-attachments/assets/f97b86fb-40ed-4cf8-b597-cc88ff304438" /> |<img width="436" height="351" alt="image" src="https://github.com/user-attachments/assets/4ef2c01a-0cb7-4798-b476-45d98a8ba60b" />
| <img width="634" height="905" alt="image" src="https://github.com/user-attachments/assets/53fae4c0-9cb0-494f-9b28-4b731f51b169" /> |<img width="646" height="904" alt="image" src="https://github.com/user-attachments/assets/836cd1c4-9f11-4aa7-b713-3f4799b81930" />
> climbingTiles: overlap icons in zoom 15+
