- src/components/Panel/FeatureHeading.js
- src/components/Panel/Panel.js
- src/components/Panel/Property.js
- src/components/Panel/TagsTable.js
- src/components/Panel/renderers/OpeningHoursRenderer.js
- src/components/Panel/renderers/PhoneRenderer.js
- src/components/Panel/renderers/WebsiteRenderer.js
WIP
Compare:
- https://osmapp-git-panel-gui.zbycz.now.sh/node/2270497637
- https://osmapp.org/node/2270497637
> Panel: update user interface

- src/components/FeaturePanel/EditDialog/EditDialog.tsx
Thanks to Petr Vozdecký for suggestion.
> EditDialog: remove confusing FeatureTypeSelect

- src/components/Map/behaviour/useInitMap.tsx
Please vote with 👍  if you like 2x faster.
Vote in  https://github.com/zbycz/osmapp/pull/52  if you like 4x faster.
If you like current speed at [osmapp.org](https://osmapp.org), add 👎  emoji reaction.
> Map: set wheelZoom to be 2x faster

- src/components/FeaturePanel/helpers.tsx
Link to the Get Information About Schools website for a ref:edubase entry
> Make ref:edubase into links

- src/components/Map/styles/basicStyle.ts
This adds house numbers to the style.
> BasicStyle: Add house numbers

- next.config.js
- src/locales/it.js
Please verify that _src/locales/it.js_ doesn't contain any syntax error (I have just modified _src/locales/vocabulary.js_ with a simple text editor).
> Add Italian translation

- src/components/Map/BrowserMap.tsx
- src/locales/vocabulary.js
> locales: update webgl_error

- src/helpers/TitleAndMetaTags.tsx
Current state:
This PR should change it like this:
fixes #129
> App: update title and description

- src/components/SearchBox/SearchBox.tsx
> SearchBox: fix missing query encoding

- src/locales/fr.js
Updated French
(Haven't updated Wiki links, they are still in English)
Thanks for your work! 😉
> Updated fr.js

- src/components/LayerSwitcher/osmappLayers.tsx
> Use the new satellite

- .gitignore
- src/components/LayerSwitcher/osmappLayers.tsx
- src/components/Map/MapFooter/MapFooter.tsx
- src/components/Map/MapFooter/MaptilerLogo.tsx
- src/components/utils/MapStateContext.tsx
- src/locales/vocabulary.js
The MapFooter attribution is rendered wrong on the server. It should be perhaps empty.. 🤔 
> Error: Hydration failed because the initial UI does not match what was rendered on the server.
> Warning: Expected server HTML to contain a matching <span> in <div>.
> layers: Add attribution to layers

- src/components/SearchBox/SearchBox.tsx
- src/components/SearchBox/onSelected.ts
Refactoring suggetsion for https://github.com/zbycz/osmapp/pull/167
For better readability, perhaps check each commit separately.
> Tailwind searchbox suggestions

- src/components/FeaturePanel/IdSchemeFields.tsx
> Fixes the contrast issue

- src/components/FeaturePanel/renderers/FoodHygieneRatingScheme.tsx
- src/helpers/theme.tsx
- src/services/__tests__/fhrsApi.test.ts
> FeaturePanel: small refactorings of FHRS

- src/components/FeaturePanel/renderers/FoodHygieneRatingScheme.tsx
This group import is too much for vercel SSR. It usually timeouts after 10 seconds with error 504.
> FeaturePanel: fix import in FHRS

- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/SearchBox.tsx
- src/components/SearchBox/onSelectedFactory.ts
> SearchBox: add loader for overpass queries

- src/services/osmApiAuth.ts
> osmApi: fix edit URL

- src/components/Map/styles/layers/overpassLayers.ts
- src/components/SearchBox/SearchBox.tsx
- src/services/__tests__/overpassSearch.test.ts
- src/services/fetch.ts
- src/services/getCenter.ts
- src/services/overpassSearch.ts
- src/services/types.ts
followup to https://github.com/zbycz/osmapp/pull/186
part of https://github.com/zbycz/osmapp/issues/191
> SearchBox: render relations in category search

- src/components/App/App.tsx
- src/components/FeaturePanel/ImageSection/ImageSection.tsx
- src/components/FeaturePanel/ImageSection/PoiDescription.tsx
- src/components/FeaturePanel/ImageSection/StarButton.tsx
- src/components/FeaturePanel/ImageSection/utils.tsx
- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/SearchBox.tsx
- src/components/SearchBox/onSelectedFactory.ts
- src/components/SearchBox/renderOptionFactory.tsx
- src/components/utils/StarsContext.tsx
- src/helpers/featureLabel.ts
- src/locales/vocabulary.js
Currently show only when searchbox is empty. Followup would be to search through them.
btw, localStorage size limit si usually ~5MB, so we are safe :)
> Stars: add to SearchBox and FeaturePanel

- src/components/HomepagePanel/HomepagePanel.tsx
- src/locales/cs.js
- src/locales/de.js
- src/locales/vocabulary.js
> HomepagePanel: add disclaimer, not an official app

- src/components/FeaturePanel/Climbing/Editor/Points/Point.tsx
- src/components/FeaturePanel/Climbing/Editor/Points/UnfinishedPoint.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteFloatingMenu.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteMarks.tsx
- src/components/FeaturePanel/Climbing/contexts/osmToClimbingRoutes.ts
- src/components/FeaturePanel/Climbing/types.ts
> climbing: add unfinished point type

- src/components/LayerSwitcher/LayerSwitcherContent.tsx
- src/components/LayerSwitcher/Overlays.tsx
- src/components/LayerSwitcher/helpers.tsx
- src/components/LayerSwitcher/osmappLayers.tsx
- src/components/Map/behaviour/useUpdateStyle.tsx
> LayerSwitcher: add overlays

- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
> Revert "climbing: Fix photo url"

- src/components/Map/behaviour/useUpdateStyle.tsx
This was killing the whole application when overpass failed.
> Map: add error handler for Climbing layer

- src/components/LayerSwitcher/osmappLayers.tsx
- src/locales/am.js
- src/locales/cs.js
- src/locales/de.js
- src/locales/es.js
- src/locales/fr.js
- src/locales/it.js
- src/locales/pl.js
- src/locales/vocabulary.js
This fixes #241.
I can only speak English and German, but for languages I can't understand i also replaced "Mapnik" with "Carto". There may be errors there but I don't know.
> Replace mapnik with carto

- src/components/FeaturePanel/Coordinates.tsx
- src/components/Map/BrowserMap.tsx
- src/components/Map/behaviour/useFeatureMarker.tsx
- src/components/Map/behaviour/useOnMapClicked.tsx
- src/components/Map/behaviour/useOnMapLongPressed.tsx
- src/components/Map/behaviour/useToggleTerrainControl.tsx
- src/components/Map/behaviour/useUpdateStyle.tsx
- src/components/Map/behaviour/useUpdateViewOnMove.tsx
- src/components/helpers.tsx
On mobile device: 
- long press shows blue coordinates pin + button
- every other click hides it
On not mobile:
- first click shows it, second hides it
> Map: add long press for coords feature

- src/components/FeaturePanel/ImageSection/PoiDescription.tsx
> FeaturePanel: fix PoiDescription color in ImageSection

- src/components/Map/BrowserMap.tsx
- src/components/Map/helpers.ts
> BrowserMap: fix `too many webgl contexts`

- src/components/Map/behaviour/useInitMap.tsx
- src/components/Map/useAddTopRightControls.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> Map: hide compass only in mobileMode

- README.md
- src/locales/am.js
- src/locales/cs.js
- src/locales/es.js
- src/locales/fr.js
- src/locales/it.js
- src/locales/pl.js
- src/locales/vocabulary.js
Uppercase G and H in GitHub occurrences
> Fix GitHub uppercase

- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/options/geocoder.tsx
- src/components/SearchBox/options/stars.tsx
- src/components/SearchBox/renderOptionFactory.tsx
- src/components/SearchBox/utils.tsx
`+ fix bug with useMapCenter called out of render function`
> SearchBox: add distance for Star options

- src/components/Map/Map.tsx
- src/components/Map/MapFooter/AttributionLinks.tsx
- src/components/Map/MapFooter/ClimbingLegend.tsx
- src/components/Map/MapFooter/MapDataLink.tsx
- src/components/Map/MapFooter/MapFooter.tsx
- src/components/helpers.tsx
`+hide shadow when collapsed`
`+fix bug - empty space when climbing layer off`
`+refactor`
> MapFooter: fix legend icon showing incorrectly + refactor

- package.json
- src/components/Map/consts.ts
- src/components/SearchBox/AutocompleteInput.tsx
- src/components/utils/MapStateContext.tsx
- src/components/utils/SnackbarContext.tsx
- yarn.lock
> general: update maplibre-gl + minor fixes

- src/services/__tests__/osmApi.fixture.ts
- src/services/__tests__/osmApi.test.ts
- src/services/osmApi.ts
- src/services/overpass/fetchOverpassCenter.ts
Thanks kindly to @mmd-osm for suggesting a proper query for that.
see https://github.com/drolbr/Overpass-API/issues/733
> osmApi: compute center for relation of relations

- src/components/FeaturePanel/PublicTransport/requestRoutes.ts
This fixes #325 
https://osmapp-d9kjcss1e-osm-app-team.vercel.app/node/3329758745#17.00/49.1976/16.6057
> FeaturePanel: order public transport routes

- src/components/App/Loading.tsx
- src/components/Map/behaviour/useOnMapClicked.tsx
- src/components/helpers.tsx
- src/services/types.ts
> App: show loading bar also for fetching feature

- src/components/FeaturePanel/Climbing/Editor/RouteDifficulty.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteWithLabel.tsx
- src/components/HomepagePanel/UserSettingsDialog.tsx
- src/components/utils/UserSettingsContext.tsx
> climbing: Show grades on photos

- src/components/FeaturePanel/Climbing/ConvertedRouteDifficultyBadge.tsx
- src/components/FeaturePanel/Climbing/RouteDifficultyBadge.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListRow.tsx
- src/components/FeaturePanel/Climbing/utils/grades/gradeSystem.ts
- src/components/FeaturePanel/Climbing/utils/grades/routeGrade.ts
- src/components/FeaturePanel/FeaturePanelInner.tsx
- src/components/FeaturePanel/FeaturedTag.tsx
- src/components/FeaturePanel/OsmError.tsx
- src/components/FeaturePanel/Properties/Properties.tsx
- src/components/FeaturePanel/renderers/ClimbingRenderer.tsx
- src/components/MyTicksPanel/MyTicksRow.tsx
- src/components/utils/openClimbingUtils.tsx
- src/locales/vocabulary.js
- src/services/tagging/idTaggingScheme.ts
> ClimbingRenderer: Add renderer for climbing grades

- src/components/FeaturePanel/Climbing/Editor/GalleryControls.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesEditor.tsx
> ClimbingEditor: Add prev/next buttons

- src/components/Map/helpers.ts
Airports weren't clickable on the map. This pr makes them clickable
> Map: Make airports clickable

- src/components/Map/BrowserMap.tsx
- src/components/Map/Map.tsx
- src/components/Map/behaviour/useUpdateStyle.tsx
- src/components/utils/MapStateContext.tsx
This reverts commit 2553afbc (#491)
> Map: fix setStyle() `diff` was always false

- src/components/SearchBox/onSelectedFactory.ts
https://github.com/zbycz/osmapp/issues/505
> SearchBox: log errors from overpass to console (+sentry)

- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/ClimbingViewContent.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteList.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListDndContent.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListRow.tsx
- src/components/FeaturePanel/Climbing/config.ts
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/FeaturePanel/Climbing/utils/array.ts
- src/components/HomepagePanel/UserSettingsDialog.tsx
- src/components/utils/UserSettingsContext.tsx
> RouteList: Selecting climbing route by scroll

- src/helpers/featureLabel.ts
- src/services/helpers.ts
Example 
https://osmapp.org/node/296750971
> FeaturePanel: show address label instead of generic "Address"

- package.json
- src/components/FeaturePanel/Climbing/RouteList/RouteListRow.tsx
- src/components/Map/MapFooter/AttributionLinks.tsx
- src/components/Map/MapFooter/MapDataLink.tsx
- yarn.lock
I've installed `@types/lodash` to provide an easier and safer experience while developing
> general: Add types to lodash

- src/components/FeaturePanel/Climbing/ClimbingViewContent.tsx
- src/components/FeaturePanel/Climbing/CragMap.tsx
- src/components/Map/behaviour/useInitMap.tsx
- src/components/Map/styles/layers/climbingLayers.ts
- src/services/osmApi.ts
> climbing: add Map to CragDialog

- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesEditor.tsx
> RouteList: Switch photos automatically

- src/components/FeaturePanel/Climbing/ClimbingGuideInfo.tsx
- src/components/FeaturePanel/Climbing/ClimbingRestriction.tsx
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
- src/components/FeaturePanel/MemberFeatures/MemberFeatures.tsx
- src/components/utils/TooltipButton.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> climbing: Add ClimbingInfoGuide

- src/components/FeaturePanel/Properties/IdSchemaFields.tsx
- src/components/FeaturePanel/Properties/TagsTableInner.tsx
- src/components/FeaturePanel/Properties/renderValue.tsx
- src/services/tagging/__tests__/idTaggingScheme.test.ts
- src/services/tagging/fields.ts
- src/services/tagging/idTaggingScheme.ts
While the labels were already internationalized the values weren't. The code was already written but never actually applied due to a small logic error.
Now units and translated values are shown in the feature panel.
| Language | Old                                                                                             | New                                                                                             |
| -------- | ----------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- |
| German   | ![old_german](https://github.com/user-attachments/assets/ef46480a-21f9-4710-946b-5ac9f940c160)  | …
> FeaturePanel: Id tagging scheme internationalization

- pages/_document.tsx
- src/helpers/FaviconsOpenClimbing.tsx
- src/helpers/FaviconsOsmapp.tsx
> appStatusBar: Update background color

- src/components/SearchBox/options/geocoder.tsx
Fixes https://github.com/zbycz/osmapp/issues/226
> SearchBox: fix missing results on Photon geocoder

- src/components/Directions/routing/getGraphhopperResults.ts
via https://github.com/graphhopper/graphhopper/issues/3052
We don't want the router to start a route in the middle of a ferry.
> Directions: add snap_prevention=ferry

- src/assets/GithubIcon.tsx
- src/components/Directions/DirectionsBox.tsx
- src/components/Map/BrowserMap.tsx
- src/components/Map/behaviour/useFeatureMarker.tsx
- src/components/Map/behaviour/useOnMapClicked.tsx
- src/components/Map/behaviour/useUpdateStyle.tsx
- src/components/Map/behaviour/useUpdateViewOnMove.tsx
- src/components/SearchBox/onSelectedFactory.ts
- src/components/helpers.tsx
- src/components/utils/ClosePanelButton.tsx
- src/components/utils/Drawer.tsx
- src/components/utils/FeatureContext.tsx
- src/components/utils/Maki.tsx
- src/components/utils/MapStateContext.tsx
- src/components/utils/MobilePageDrawer.tsx
- src/components/utils/SnackbarContext.tsx
- src/components/utils/StarsContext.tsx
- src/components/utils/UserSettingsContext.tsx
- src/components/utils/colorUtils.tsx
- src/components/utils/nl2br.tsx
- src/components/utils/usePersistedState.ts
- yarn.lock
As described in #571 add types.
*Only internal changes, no checklist is needed*
> Types: Add a bunch of types

- src/components/FeaturePanel/Properties/getUrlForTag.tsx
Make e-mail addresses clickable.
> FeaturePanel: Make email addreses clickable

- src/components/FeaturePanel/Properties/IdSchemaFields.tsx
- src/components/FeaturePanel/Properties/TagsTableInner.tsx
- src/components/FeaturePanel/Properties/renderValue.tsx
- src/services/tagging/__tests__/idTaggingScheme.test.ts
- src/services/tagging/fields.ts
- src/services/tagging/idTaggingScheme.ts
Apply the translations and units in the id tagging scheme. Also fixed the issues I've accidentally introduced in #559
> FeaturePanel: Id tagging scheme internationalization (fixes)

- src/components/FeaturePanel/Climbing/useGetHandleSave.tsx
- src/components/FeaturePanel/EditDialog/EditContent/OtherTagsEditor.tsx
- src/components/FeaturePanel/MemberFeatures/ClimbingItem.tsx
> climbing: Fix saving crag & tags maxlength

- package.json
- src/components/App/App.tsx
- src/components/FeaturePanel/Climbing/utils/useScrollShadow.tsx
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
- src/components/FeaturePanel/FeaturePanelInDrawer.tsx
- src/components/FeaturePanel/FeaturePanelOnSide.tsx
- src/components/utils/Drawer.tsx
- src/components/utils/PanelHelpers.tsx
- yarn.lock
> FeaturePanel: Scroll to top after click on the link

- src/components/App/App.tsx
- src/components/FeaturePanel/FeaturePanelInDrawer.tsx
- src/components/utils/Drawer.tsx
- src/components/utils/PanelHelpers.tsx
> FeaturePanel: Fix scrollbars

- src/components/App/App.tsx
- src/components/FeaturePanel/Climbing/ClimbingStructuredData.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
> structured data: Add structured data for climbing areas/crags/routes

- src/components/Map/behaviour/useFeatureMarker.tsx
> feature preview: Fix preview bug

- src/components/FeaturePanel/Climbing/utils/photo.ts
> wikimedia: Don't render categories on wikimedia

- src/components/FeaturePanel/EditDialog/EditContent/MajorKeysEditor.tsx
- src/components/FeaturePanel/EditDialog/EditDialog.tsx
- src/locales/vocabulary.js
> EditDialog: Add character count and description

- src/components/FeaturePanel/Climbing/ClimbingStructuredData.tsx
> structured data: Fix structured data deletion

- src/components/FeaturePanel/Climbing/Editor/RouteNumber.tsx
- src/components/FeaturePanel/Climbing/RouteNumber.tsx
- src/components/FeaturePanel/Climbing/utils/useRouteNumberColors.tsx
> climbing tick: Show ticked routes on photos

- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
- src/components/FeaturePanel/MemberFeatures/ClimbingItem.tsx
> FeaturePanel: Fix margin bug

- src/components/Map/MapFooter/MapFooter.tsx
> ClimbingLegend: Set default visibility to false

- src/components/utils/PanelHelpers.tsx
It was not possible to scroll all the way down on desktop in the featurepanel
> FeaturePanel: Fix scroll bug

- src/components/FeaturePanel/PublicTransport/PublicTransport.tsx
- src/components/FeaturePanel/PublicTransport/PublicTransportWrapper.tsx
- src/components/FeaturePanel/PublicTransport/requestRoutes.ts
- src/locales/de.js
- src/locales/vocabulary.js
Add a category for subways using the `subway=yes` tag
https://osmapp-1xwc9adwu-osm-app-team.vercel.app/node/30353880
> FeaturePanel: Add a category for subways

- src/components/FeaturePanel/EditDialog/EditContent/OpeningHoursEditor/parser/__tests__/parser.test.ts
- src/components/FeaturePanel/EditDialog/EditContent/OpeningHoursEditor/parser/canItHandle.ts
- src/components/FeaturePanel/EditDialog/EditContent/OpeningHoursEditor/parser/getDaysTable.ts
https://osmapp.org/way/379512802
`Mo off; Tu-Sa 10:00-13:00, 15:00-17:00; Su 10:30-12:00`
> OpeningHoursEditor: skip auxiliary `Mo off;`

- package.json
- src/components/Map/behaviour/useUpdateStyle.tsx
- yarn.lock
Fixes #460
Amharic
Spanish
- [] new dependencies are reasoned about in PR comments
> Map: Use localized names

- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListDndContent.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListRow.tsx
> RouteList: Add deselect button

- src/components/FeaturePanel/Climbing/ClimbingCragDialog.tsx
- src/components/FeaturePanel/Climbing/ClimbingCragDialogHeader.tsx
- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/Editor/ControlPanel.tsx
- src/components/FeaturePanel/Climbing/Guide.tsx
- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListRow.tsx
- src/locales/vocabulary.js
> Climbing Guide: Update UX

- src/components/FeaturePanel/Climbing/ClimbingCragDialog.tsx
- src/components/FeaturePanel/Climbing/ClimbingEditorHelperText.tsx
https://openclimbing.org/relation/17225520/climbing/photo/Ko%C5%A1%C3%AD%C5%99e%20-%20Skalka.jpg#17.00/50.0705/14.3621
| old | new |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/cd4b9834-c9a7-4be3-9895-57599e2e7341) | ![image](https://github.com/user-attachments/assets/0c0ea84c-833b-4021-84c7-ff8e161d8c23) |
> climbing: shrink ClimbingEditorHelperText

- src/components/FeaturePanel/Climbing/ClimbingCragDialog.tsx
- src/components/FeaturePanel/Climbing/ClimbingCragDialogHeader.tsx
- src/components/FeaturePanel/Climbing/ClimbingEditorHelperText.tsx
> ClimbingDialog: Add DrawButton on mobile

- src/components/FeaturePanel/Climbing/Editor/RoutePath.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
> ClimbingEditor: Fix Firefox bug

- src/components/FeaturePanel/Climbing/ClimbingEditorHelperText.tsx
- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListRow.tsx
> ClimbingEditorHelperText: Fix conditions and UX

- src/components/FeaturePanel/Climbing/Editor/Points/Point.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutePath.tsx
> ClimbingEditor: Delete hover on mobile

- src/components/FeaturePanel/EditDialog/EditContent/MajorKeysEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/helpers.tsx
- edit description here: https://osmapp.org/relation/17262675
> EditDialog: show CharacterCount only for >= 150 chars

- src/components/FeaturePanel/FeaturedTag.tsx
See `op:node[~"description"~"\n"]`
https://osmapp.org/node/3408157858
> FeaturePanel: add nl2br helper for `description` FeaturedTag

- src/components/FeaturePanel/Climbing/ClimbingViewContent.tsx
> ClimbingView: Add EditButton

- src/components/FeaturePanel/EditDialog/EditContent/EditDialogActions.tsx
- src/components/FeaturePanel/EditDialog/EditContent/OsmUserLoggedOut.tsx
- src/locales/vocabulary.js
> EditDialog: Add loading alert

- src/components/FeaturePanel/EditDialog/EditContent/OsmUserLoggedOut.tsx
- src/locales/vocabulary.js
> EditDialog: Update button wrap

- src/components/SearchBox/consts.ts
- src/components/SearchBox/options/openstreetmap.tsx
- src/components/SearchBox/options/preset.tsx
- src/components/SearchBox/options/stars.tsx
- src/components/SearchBox/renderOptionFactory.tsx
- src/components/SearchBox/types.ts
- src/components/SearchBox/utils.tsx
Optimized filtering:
1. Higher threshold for the dice coefficient
2. Don't add up all all alternative names
3. Make the osm options only appear when wanted
This fixes #657
> SearchBox: Optimized filtering

- src/components/FeaturePanel/ObjectsAround.tsx
- src/components/FeaturePanel/helpers/importance.ts
- src/services/osmApi.ts
- src/services/overpassSearch.ts
This fixes #669. Important features are now prioritized. To determine how important a feature is the sum of all tag importances is used. The importance of a tag is determined either using a static value or using a simple function.
https://osmapp-m8sep9ahu-osm-app-team.vercel.app/14.604300,121.031612
https://osmapp-m8sep9ahu-osm-app-team.vercel.app/50.113607,8.679126
https://osmapp-m8sep9ahu-osm-app-team.vercel.app/way/293705698
| New                                                                                       | Old                                                                                       |
| ----------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------- …
> FeaturePanel: Prioritize important POI

- src/components/LayerSwitcher/AddCustomLayer.tsx
Unify Add custom layer cancel button with buttons from edit dialog.
edit dialog:
add layer dialog:
> Unify Add custom layer cancel button

- src/components/FeaturePanel/Properties/getUrlForTag.tsx
- src/services/images/getImageDefs.ts
- src/services/images/getImageFromApi.ts
- src/services/images/getMapillaryImage.ts
Fix #705 by supporting tagged panoramax and mapillary images.
[Panoramax](https://osmapp-d7e3t73j7-osm-app-team.vercel.app/node/12234408704)
[Mapillary](https://osmapp-d7e3t73j7-osm-app-team.vercel.app/node/4960463923)
> Images: Tagged mapillary and panoramax

- src/components/FeaturePanel/renderers/OpeningHoursRenderer.tsx
- src/components/FeaturePanel/renderers/openingHours/complex.ts
Opening hours that are by appointment previously didn't work correctly as it was observed in #711 
This now fixes this issue
[Only by appointment](https://osmapp-git-fork-dlurak-opening-hours-by-app-fdbbf6-osm-app-team.vercel.app/node/5562025232)
[Hours + by appointment](https://osmapp-git-fork-dlurak-opening-hours-by-app-fdbbf6-osm-app-team.vercel.app)
> FeaturePanel: Add support for by appointment to the opening hours

- src/components/Directions/DirectionsBox.tsx
- src/components/Directions/Instructions.tsx
- src/components/Directions/Result.tsx
- src/components/Directions/helpers.tsx
- src/components/Directions/routing/getGraphhopperResults.ts
- src/components/Directions/routing/instructions.ts
- src/components/Directions/routing/types.ts
Show instructions when creating a route
> Directions: Add instructions

- src/components/HomepagePanel/HomepageOpenClimbing.tsx
- src/components/HomepagePanel/HomepageOpenClimbingGallery.tsx
- src/locales/cs.js
> Homepage: Fix text bug

- src/components/Directions/DirectionsButton.tsx
- src/components/SearchBox/SearchBox.tsx
In mobile mode i left it hidden, there are already to many buttons.
- Where does this button belong in mobile mode?
> SearchBox: add DirectionsButton when nothing shown

- src/components/FeaturePanel/EditDialog/EditContent/EditDialogActions.tsx
- src/components/FeaturePanel/EditDialog/EditContent/MajorKeysEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/OpeningHoursEditor/OpeningHoursEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/OpeningHoursEditor/OpeningHoursInput.tsx
- src/components/FeaturePanel/EditDialog/EditContent/OpeningHoursEditor/YoHoursLink.tsx
- src/components/FeaturePanel/EditDialog/EditContent/OptionsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/PresetSearchBox.tsx
- src/components/FeaturePanel/EditDialog/EditContent/PresetSelect.tsx
- src/components/FeaturePanel/EditDialog/EditContent/TagsEditor/KeyInput.tsx
- src/components/FeaturePanel/EditDialog/EditContent/TagsEditor/TagsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/TagsEditor/ValueInput.tsx
- src/components/FeaturePanel/EditDialog/EditContext.tsx
- src/components/FeaturePanel/EditDialog/EditDialog.tsx
- src/components/FeaturePanel/EditDialog/useGetHandleSave.tsx
- src/services/osmApiAuth.ts
change cancelled to toBeDeleted Pavel Zbytovský A minute ago
change context.tags to context.data Pavel Zbytovský Today 14:31
EditDialog: small refactors Pavel Zbytovský Today 14:25
> EditDialog: small refactors

- src/services/helpers.ts
- src/services/osmApiAuth.ts
> EditDialog: osmApiAuth types + remove redundant fetchJson()

- pages/climbing-grades.ts
- src/components/App/App.tsx
- src/components/FeaturePanel/Climbing/ClimbingGradesTable.tsx
- src/components/FeaturePanel/Climbing/GradeSystemSelect.tsx
- src/components/Map/TopMenu/HamburgerMenu.tsx
- src/components/utils/UserSettingsContext.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
resolves https://github.com/zbycz/osmapp/issues/741
> ClimbingGradesTable: Add climbing grades table

- src/components/SearchBox/getOptionLabel.tsx
- src/components/SearchBox/options/openstreetmap.tsx
Matching url like https://openstreetmap.org/node/967531 was broken, should be fixed.
> SearchBox: fix url matching for osm.org

- src/components/LayerSwitcher/AddCustomLayer.tsx
- src/components/LayerSwitcher/BaseLayers.tsx
- src/components/LayerSwitcher/LayerSwitcherContent.tsx
- src/components/LayerSwitcher/Overlays.tsx
- src/components/LayerSwitcher/helpers.tsx
- src/components/LayerSwitcher/helpers/loadLayers.ts
- src/components/LayerSwitcher/osmappLayers.tsx
- src/components/utils/MapStateContext.tsx
- src/services/__tests__/overpassSearch.test.ts
- src/services/overpassSearch.ts
Refactoring and few small fixes. No visual change.
> LayerSwitcher: refactoring - extract BaseLayers

- .github/pull_request_template.md
I noticed we often forget this, maybe checklist will help 😅
> general: add localization to pull_request_template.md

- src/components/FeaturePanel/Climbing/ClimbingGradesTable.tsx
- src/components/FeaturePanel/Climbing/utils/grades/routeGrade.ts
> Climbing: Fix bug with approx grading

- src/components/FeaturePanel/Climbing/ClimbingStructuredData.tsx
- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/ClimbingViewContent.tsx
- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
- src/components/FeaturePanel/Climbing/config.ts
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/FeaturePanel/Climbing/utils/useCragViewLayout.tsx
- src/components/HomepagePanel/UserSettingsDialog.tsx
- src/components/utils/UserSettingsContext.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> ClimbingView: Add layout option

- src/components/FeaturePanel/Climbing/Editor/Points/Point.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesEditor.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
> ClimbingEditor: Optimize editor for mobile devices

- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/Editor/Points/Point.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteFloatingMenu.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutePath.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesEditor.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
- src/components/FeaturePanel/Climbing/TransformWrapper.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/FeaturePanel/Climbing/utils/mousePositionUtils.ts
- src/components/FeaturePanel/Climbing/utils/useGetMachineFactory.ts
> Climbing: Bug fixes in ClimbingEditor

- src/components/FeaturePanel/Climbing/ClimbingCragDialogHeader.tsx
- src/components/FeaturePanel/Climbing/PhotoLink.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/FeaturePanel/Climbing/useGetHandleSave.tsx
- src/components/FeaturePanel/Climbing/utils/array.ts
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/FeaturePanel/FeatureImages/FeatureImages.tsx
- src/services/osmApiAuth.ts
> ClimbingView: sortable photos

- src/components/FeaturePanel/Climbing/ClimbingCragDialogHeader.tsx
- src/components/FeaturePanel/Climbing/useGetHandleSave.tsx
- src/services/osmApiAuth.ts
> ClimbingView: Fix sortable photos

- src/components/FeaturePanel/Climbing/ClimbingCragDialogHeader.tsx
- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/FeaturePanel/Climbing/utils/photo.ts
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/FeaturePanel/FeatureImages/FeatureImages.tsx
> ClimbingView: Fix natural sort in photos

- src/components/FeaturePanel/Climbing/ClimbingCragDialogHeader.tsx
- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/PhotoLink.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/FeaturePanel/Climbing/useGetHandleSave.tsx
- src/components/FeaturePanel/Climbing/utils/array.ts
- src/components/FeaturePanel/Climbing/utils/photo.ts
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/FeaturePanel/FeatureImages/FeatureImages.tsx
- src/services/osmApiAuth.ts
It breaks opening any way or relation in the map, eg
`/relation/3075632`
> Revert "ClimbingView: sortable photos..."

- src/components/Directions/DirectionsAutocomplete.tsx
> Directions: Add my position to autocomplete

- src/components/Directions/DirectionsBox.tsx
> Directions: Improve responsiveness

- src/components/App/App.tsx
- src/components/Directions/DirectionsAutocomplete.tsx
- src/components/Directions/DirectionsBox.tsx
- src/components/Directions/DirectionsContext.tsx
- src/components/Directions/DirectionsForm.tsx
- src/components/Directions/Result.tsx
- src/components/Directions/useGetOnSubmit.tsx
> Directions: Auto recalculate direction on marker drag

- src/components/Directions/DirectionsAutocomplete.tsx
> Directions: Update route on autocomplete item click

- src/components/Directions/DirectionsForm.tsx
> Directions: Update route on map click

- src/components/FeaturePanel/EditDialog/useEditItems.tsx
- src/components/Map/styles/layers/overpassLayers.ts
- src/components/SearchBox/options/overpass.tsx
- src/services/overpassSearch.ts
- remove fill for polygons https://github.com/zbycz/osmapp/issues/739
- for Polygons move text placement to the center
- remove points without tags
`op:nwr`
| old | new |
| -- | -- |
| <img width="781" alt="image" src="https://github.com/user-attachments/assets/c6589069-d342-44dc-abcd-eaab6d58c7b6"> | <img width="786" alt="image" src="https://github.com/user-attachments/assets/625436e0-6094-4054-9f2f-ea66cceb0b06">
> Map: tweak overpass search results

- src/components/FeaturePanel/EditDialog/EditContent/EditContent.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/FeatureEditSection.tsx
- src/components/FeaturePanel/EditDialog/EditContent/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContext.tsx
- src/components/utils/FeatureContext.tsx
https://github.com/user-attachments/assets/d0492491-51e0-48b1-8ce5-f77c84fa5478
> Edit dialog add members

- src/components/FeaturePanel/EditDialog/EditContent/CommentField.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ContributionInfoBox.tsx
- src/components/FeaturePanel/EditDialog/EditContent/EditContent.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/FeatureEditSection.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/OptionsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/TagsEditor/TagsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureRow.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ParentsEditor.tsx
- src/locales/vocabulary.js
- src/services/osmApi.ts
> EditDialog: Add parents

- src/components/FeaturePanel/Climbing/contexts/osmToClimbingRoutes.ts
- src/components/FeaturePanel/Climbing/utils/getDividedFeaturesBySections.ts
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/FeaturePanel/MemberFeatures/MemberFeatures.tsx
Fixes https://github.com/zbycz/osmapp/issues/842
> FeaturePanel: Fix showing non-climbing routes

- src/components/Directions/DirectionsForm.tsx
- src/components/FeaturePanel/Climbing/ClimbingCragDialogHeader.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListDndContent.tsx
- src/components/utils/DragHandler.tsx
- src/components/utils/useDragItems.tsx
> Directions: Change order

- src/components/FeaturePanel/Climbing/CameraMarker.tsx
- src/components/FeaturePanel/Climbing/ClimbingViewContent.tsx
- src/components/FeaturePanel/Climbing/CragMap.tsx
- src/components/FeaturePanel/Climbing/RouteDistribution.tsx
- src/components/FeaturePanel/Climbing/utils/photo.ts
- src/locales/vocabulary.js
> CragMap: Add photo locations to crag map view

- src/components/FeaturePanel/PublicTransport/routes/CategoryHeading.tsx
- src/components/FeaturePanel/PublicTransport/routes/Routes.tsx
- src/locales/de.js
- src/locales/vocabulary.js
Fix #815 by adding a trolleybus category
https://osmapp.org/node/645611754
> PublicTransport: Add a trolleybus category

- src/components/FeaturePanel/Properties/Direction.tsx
Add support for showing multiple arrows for the direction tag in the Feature panel.
https://osmapp.org/node/7059320839
> FeaturePanel: Add support for multiple directions values

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/FeatureEditSection.tsx
- src/components/FeaturePanel/EditDialog/EditContent/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ParentsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/helpers.tsx
- src/services/osmApi.ts
- src/services/types.ts
Fixes clicking on members and parents. Always fetches fresh "full" feature.
Adds getFullFeatureWithMemberFeatures() fn
> EditDialog: use getFullFeatureWithMemberFeatures in MembersEditor and ParentsEditor

- public/openclimbing/taginfo.json
> Add taginfo for openclimbing

- src/components/FeaturePanel/ObjectsAround.tsx
- src/components/FeaturePanel/PublicTransport/routes/requestRoutes.ts
- src/components/SearchBox/onSelectedFactory.ts
- src/services/__tests__/overpassAroundToSkeletons.test.ts
- src/services/__tests__/overpassSearch.test.ts
- src/services/climbing-areas/getClimbingAreas.ts
- src/services/my-ticks/getMyTicks.ts
- src/services/osm/osmApi.ts
- src/services/overpass/fetchAroundFeatures.ts
- src/services/overpass/fetchOverpassCenter.ts
- src/services/overpass/overpassAroundToSkeletons.ts
- src/services/overpass/overpassSearch.ts
> osmApi: refactor – move to `services/overpass` folder

- pages/api/og-image.tsx
- src/components/FeaturePanel/EditDialog/EditContent/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ParentsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/helpers.tsx
- src/components/FeaturePanel/EditDialog/useGetHandleSave.tsx
- src/components/Map/behaviour/maptilerFix.tsx
- src/components/Map/behaviour/useOnMapClicked.tsx
- src/components/SearchBox/onSelectedFactory.ts
- src/services/osm/__tests__/osmApi.test.ts
- src/services/osm/featureCenterToCache.ts
- src/services/osm/fetchParentFeatures.ts
- src/services/osm/fetchWithMemberFeatures.ts
- src/services/osm/getCountryCode.ts
- src/services/osm/getFullFeatureWithMemberFeatures.ts
- src/services/osm/helpers.ts
- src/services/osm/insertOsmNote.ts
- src/services/osm/osmApi.ts
- src/services/osm/quickFetchFeature.ts
- src/services/osm/types.ts
- src/services/osm/urls.ts
> osmApi: refactor – break up `osmApi.ts`

- src/components/FeaturePanel/EditDialog/EditContent/ParentsEditor.tsx
- src/services/osm/fetchNodesWaysFeatures.ts
- src/services/osm/fetchParentFeatures.ts
- src/services/osm/osmApiAuth.ts
- src/services/osm/types.ts
- src/services/osm/urls.ts
- src/services/tagging/idTaggingScheme.ts
/node/1249818501
/node/3170148187
> EditDialog: show parent ways for nodes

- src/components/FeaturePanel/EditDialog/EditContent/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ParentsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/helpers.tsx
> EditDialog: Open new tab with cmd click

- src/components/HomepagePanel/SupportUs.tsx
- src/services/project.tsx
> SupportUs: Add heart animation

- src/components/FeaturePanel/EditDialog/EditContent/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/MembersEditor.tsx
- src/services/getCoordsFeature.ts
> EditDialog: Create climbing/route_bottom as default member in crag

- src/components/FeaturePanel/EditDialog/EditContent/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/EditContent.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/FeatureEditSection.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureRow.tsx
- src/components/FeaturePanel/FeatureHeading.tsx
- src/components/FeaturePanel/NwrIcon.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> FeaturePanel: Add NwrIcon

- src/components/ClimbingAreasPanel/ClimbingAreasPanel.tsx
- src/components/FeaturePanel/Climbing/ClimbingGuideInfo.tsx
- src/components/FeaturePanel/Climbing/FeaturePanelClimbingGuideInfo.tsx
- src/components/FeaturePanel/FeatureHeading.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> FeaturePanel: ClimbingGuideInfo update

- src/components/FeaturePanel/Climbing/FeaturePanelClimbingGuideInfo.tsx
- src/components/FeaturePanel/Climbing/utils/climbingTagValues.ts
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
- src/components/FeaturePanel/FeaturedTags.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> FeaturePanel: Add description on the top in climbing entities

- src/components/FeaturePanel/Coordinates.tsx
- src/components/FeaturePanel/FeatureDescription.tsx
- src/components/FeaturePanel/FeaturePanelFooter.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> FeaturePanel: polish FeaturePanelFooter

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/EditFeatureMap/EditFeatureMap.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/EditFeatureMap/isGpsValid.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/EditFeatureMap/useDraggableMarker.ts
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/EditFeatureMap/useInitEditFeatureMap.ts
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/EditFeatureMap/useStaticMarkers.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> EditDialog: Add text field for setting GPS coordinates

- src/components/FeaturePanel/NwrIcon.tsx
> NwrIcon: Fix unknown type

- src/components/HomepagePanel/SupportUs.tsx
> SupportUs: Add Revolut link

- src/components/FeaturePanel/ClimbingRouteGrade.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MajorKeysEditor.tsx
- src/components/FeaturePanel/Properties/Properties.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
- src/services/osm/osmApi.ts
- src/utils.ts
> EditDialog: Add major keys for climbing route

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MajorKeysEditor.tsx
> EditDialog: Fix major keys bug

- src/components/FeaturePanel/EditDialog/EditContent/EditContent.tsx
- src/locales/cs.js
> Fix small UI bugs

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/EditFeatureMap/useStaticMarkers.tsx
> EditDialog: Fix not showing newly created relations on the map

- src/components/FeaturePanel/Climbing/ClimbingCragDialogHeader.tsx
- src/components/FeaturePanel/Climbing/ClimbingGuideInfo.tsx
- src/components/FeaturePanel/Climbing/FeaturePanelClimbingGuideInfo.tsx
- src/components/FeaturePanel/Climbing/PanelLabel.tsx
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/FeaturePanel/EditDialog/EditContent/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ParentsEditor.tsx
- src/components/FeaturePanel/FeatureHeading.tsx
- src/components/FeaturePanel/FeatureImages/FeatureImages.tsx
- src/components/FeaturePanel/FeatureImages/Image/Image.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
- src/components/FeaturePanel/FeaturedTag.tsx
- src/components/FeaturePanel/MemberFeatures/MemberFeatures.tsx
- src/components/FeaturePanel/Properties/Table.tsx
- src/components/FeaturePanel/QuickActions/QuickActionButton.tsx
- src/components/FeaturePanel/QuickActions/QuickActions.tsx
- src/components/FeaturePanel/QuickActions/ShareDialog/ShareButton.tsx
- src/components/FeaturePanel/QuickActions/ShareDialog/ShareDialog.tsx
- src/components/FeaturePanel/helpers/InlineEditButton.tsx
- src/components/FeaturePanel/helpers/PoiDescription.tsx
- src/components/HomepagePanel/Homepage.tsx
- src/components/utils/PanelHelpers.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
- src/services/tagging/ourPresets.ts
Most of the visible changes are on openclimbing.org:
> FeaturePanel: Update typography and design

- src/components/Map/behaviour/useInitMap.tsx
- src/components/Map/behaviour/useUpdateStyle.tsx
The on(style-load) event was not working properly.
> Map: set globe projection for all styles

- src/components/FeaturePanel/FeatureDescription.tsx
- src/components/FeaturePanel/FeatureHeading.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
- src/components/FeaturePanel/FeaturePanelFooter.tsx
- src/components/FeaturePanel/OsmError.tsx
| old | new
| --|--
| <img width="413" alt="image" src="https://github.com/user-attachments/assets/b3c31f9a-72e2-4954-89c2-d58e32b1f470" /> | <img width="410" alt="image" src="https://github.com/user-attachments/assets/2f5ca6f7-c4de-405e-b2a2-97d118d1125d" />
> FeaturePanel: move NwrIcon to footer + polish

- .github/workflows/pr-title-check.yml
FAILED: https://github.com/zbycz/osmapp/actions/runs/13126903730/job/36624856040?pr=919
> general: check PR title

- src/components/FeaturePanel/EditDialog/EditContent/CommentField.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ContributionInfoBox.tsx
- src/components/FeaturePanel/EditDialog/EditContent/EditContent.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> EditDialog: Improve comment UI

- src/components/FeaturePanel/Properties/IdSchemaFields.tsx
eg
https://openclimbing.org/node/12076622869
> FeaturePanel: add units only for numeric values

- src/components/FeaturePanel/EditDialog/EditContent/AddMemberForm.tsx
Undocumented feature, until we add the autocomplete input.
> EditDialog: add member by shortId

- src/components/FeaturePanel/renderers/WebsiteRenderer.tsx
> FeaturePanel: display decoded link

- src/components/FeaturePanel/Climbing/ClimbingGradesTable.tsx
- src/components/FeaturePanel/Climbing/ClimbingStructuredData.tsx
- src/components/FeaturePanel/Climbing/ConvertedRouteDifficultyBadge.tsx
- src/components/FeaturePanel/Climbing/GradeSystemSelect.tsx
- src/components/FeaturePanel/Climbing/RouteDifficultySelect.tsx
- src/components/FeaturePanel/Climbing/types.ts
- src/components/FeaturePanel/Climbing/utils/grades/gradeData.ts
- src/components/FeaturePanel/Climbing/utils/grades/gradeSystem.ts
- src/components/FeaturePanel/Climbing/utils/grades/routeGrade.ts
- src/components/FeaturePanel/FeaturePanel.tsx
- src/components/FeaturePanel/FeaturedTag.tsx
- src/components/FeaturePanel/FeaturedTags.tsx
- src/components/FeaturePanel/Properties/Properties.tsx
- src/components/FeaturePanel/renderers/ClimbingGradeRenderer.tsx
- src/components/FeaturePanel/renderers/OpeningHoursRenderer.tsx
- src/components/FeaturePanel/renderers/PhoneRenderer.tsx
- src/components/FeaturePanel/renderers/WebsiteRenderer.tsx
- src/components/utils/UserSettingsContext.tsx
- src/services/tagging/climbing.ts
- src/services/tagging/featuredKeys.ts
- src/services/tagging/idTaggingScheme.ts
- all featured tags are defined in FEATURED_TAGS
- move needed climbing grades out of Climbing folder (it will be lazy loaded in future)
eg
https://openclimbing.org/way/445009274
> FeaturePanel: refactor FeaturedTags to use regexps

- src/services/tagging/__tests__/idTaggingScheme.test.ts
- src/services/tagging/idTaggingScheme.ts
eg. type, site, image, wikipedia_commons etc.
Removes visual clutter. :tada:
> FeaturePanel: remove pointless fields

- src/services/tagging/idTaggingScheme.ts
Before:
- depending on tags order
After:
> FeaturePanel: sort FeaturedKeys properly

- src/components/Map/BrowserMap.tsx
- src/components/Map/behaviour/useUpdateStyle.tsx
- src/components/utils/SnackbarContext.tsx
> Map: show warning for OpenFreeMap

- src/components/FeaturePanel/NwrIcon.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
Try to educate 1st time users/editors. Especially in EditDialog. 
Maybe it is too technical, lets iterate on design.
> FeaturePanel: add description for NwrIcon

- src/components/FeaturePanel/CragsInArea.tsx
- src/components/FeaturePanel/FeatureImages/FeatureImages.tsx
any area - eg relation/17336989
> climbing: hide NoImage placeholder for climbing=area

- src/components/FeaturePanel/Climbing/utils/__tests__/photo.test.ts
- src/components/FeaturePanel/Climbing/utils/photo.ts
> MajorKeys: Fix wikimedia_common keys

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/AddMemberForm.tsx
> EditDialog: Add CMD for create member on background

- src/components/Map/climbingTiles/climbingLayers.ts
- src/server/climbing-tiles/db.sql
- src/server/climbing-tiles/db.ts
- src/server/climbing-tiles/overpass/overpassToGeojsons.ts
- src/server/climbing-tiles/refreshClimbingTiles.ts
- src/server/logRequest.tsx
- src/services/fetch.ts
- plus save `nameRaw` without diacritics to enable search later
> climbingTiles: add more tag combinations

- src/components/Map/Weather/DaySelector.tsx
- src/components/Map/Weather/DetailedWeather.tsx
- src/components/Map/Weather/FocusedWeather.tsx
- src/components/Map/Weather/WeatherInner.tsx
- src/components/Map/Weather/icons.ts
- src/components/Map/Weather/loadWeather.tsx
Commits:
- weather: highlight selected day
- weather: fix jumping InformationRow in FocusedWeather
- weather: fix wrong day order
- weather: fix https warning 
- weather: make sun yellow  (I was often confused what should the RED circle mean 😅 )
| was | new |
| --|--|
| ![image](https://github.com/user-attachments/assets/8d90701d-c898-49f9-9d93-8ea0164aafc8) | ![image](https://github.com/user-attachments/assets/562cbd10-104e-445c-beb5-d7cf94725dcf)
| ![image](https://github.com/user-attachments/assets/20e507d7-6901-4ad2-82d2-75d40d6ac8e4) | ![image](https://github.com/user-attachments/assets/4a06a262-9185-4233-8ad2-1ffbf8e7a00e)
> weather: highlight selected day + fixes

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/LocationEditor/EditFeatureMap.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/LocationEditor/LocationEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/LocationEditor/getMapStyle.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/LocationEditor/useInitEditFeatureMap.ts
- src/components/FeaturePanel/renderers/WebsiteRenderer.tsx
> EditFeatureMap: Add satellite map

- src/components/FeaturePanel/FeaturePanel.tsx
> FeaturePanel: Add margin to boulder badge

- src/components/App/App.tsx
- src/components/SearchBox/SearchBox.tsx
> general: unclutter App – refactor SearchBox

- src/components/App/App.tsx
- src/components/App/helpers.ts
- src/components/FeaturePanel/ResponsiveFeaturePanel.tsx
- src/components/FeaturePanel/helpers/externalLinks.ts
- src/components/Map/styles/layers/overpassLayers.ts
- src/components/utils/PanelHelpers.tsx
- src/services/overpass/overpassSearch.ts
> general: unclutter App – extract ResponsiveFeaturePanel

- src/components/App/App.tsx
- src/components/Climbing/Climbing.tsx
> general: unclutter App – extract Climbing

- src/components/App/App.tsx
- src/components/Directions/Directions.tsx
- src/components/HomepagePanel/HomepagePanel.tsx
- src/components/SearchBox/SearchBox.tsx
> general: unclutter App – extract Directions

- src/components/App/App.tsx
- src/components/utils/MapStateContext.tsx
> general: unclutter App – inline IndexWithProviders

- pages/_app.tsx
- src/components/App/umami.tsx
We have a lot of requests on osmapp and we don't know from where they are. We had to switch to paid tier on vercel so we would like know what's actually happening. It should be reverted in the future.
> Umami: Add for osmapp

- src/components/App/umami.tsx
> Umami: Fix ternary operator

- pages/index.ts
- src/components/utils/FeatureContext.tsx
> general: fix HomepagePanel not showing after click

- pages/api/climbing-tiles/refresh.ts
- pages/api/climbing-tiles/stats.ts
- pages/api/climbing-tiles/tile.ts
- pages/api/og-image.tsx
- pages/api/user.ts
- vercel.json
> general: fix error.code not in HTTP statuses

- src/components/FeaturePanel/Climbing/Editor/RouteFloatingMenu.tsx
- src/components/Map/TopMenu/HamburgerMenu.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> HamburgerMenu: Fix climbing items

- src/components/FeaturePanel/Properties/IdSchemaFields.tsx
- src/components/FeaturePanel/Properties/renderValue.tsx
- src/services/tagging/__tests__/idTaggingScheme.test.ts
- src/services/tagging/fields.ts
- src/services/tagging/idTaggingScheme.ts
- src/services/tagging/keysTodo.ts
- src/services/tagging/translations.ts
- src/services/tagging/types/Presets.ts
Was broken for https://osmapp.org/way/1200404964
> tagging: fix FieldTranslation type

- src/components/Directions/DirectionsAutocomplete.tsx
- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/onSelectedFactory.ts
- src/components/SearchBox/options/coords.tsx
- src/components/SearchBox/options/geocoder.tsx
- src/components/SearchBox/options/osm.tsx
- src/components/SearchBox/options/overpass.tsx
- src/components/SearchBox/options/preset.tsx
- src/components/SearchBox/options/stars.tsx
- src/components/SearchBox/renderOptionFactory.tsx
- src/components/SearchBox/useGetOptions.tsx
- src/components/SearchBox/utils.tsx
> SearchBox: refactor - replace renderOption with Row component

- src/components/SearchBox/AutocompleteInput.tsx
- src/helpers/hooks.ts
> SearchBox: refactor - extract AutocompleteConfigured, move focusOnSlash

- src/components/SearchBox/onHighlightFactory.ts
- src/components/SearchBox/onSelectedFactory.ts
- src/components/SearchBox/options/geocoder.tsx
- src/components/SearchBox/options/overpass.tsx
- src/components/SearchBox/options/stars.tsx
- src/components/SearchBox/types.ts
Mostly ide refactorings
add more addresses to getAdditionalText
> SearchBox: refactor - add more types for geocoder, move selected factories

- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/getOptionLabel.tsx
- src/components/SearchBox/options/osm.tsx
- src/components/SearchBox/renderInputFactory.tsx
- src/components/SearchBox/renderOptionFactory.tsx
- src/components/SearchBox/useGetOnHighlight.ts
- src/components/SearchBox/useGetOnSelected.ts
Finally AutocompleteInput looks fine.
> SearchBox: refactor - extract onHighlight+onSelected as hooks

- src/components/Directions/DirectionsAutocomplete.tsx
- src/components/SearchBox/options/geocoder.tsx
- src/components/SearchBox/options/preset.tsx
- src/components/SearchBox/useGetOptions.tsx
> SearchBox: refactor - make `fetchGeocoderOptions` return Options

- README.md
> Readme: Update README.md

- src/components/Directions/DirectionsAutocomplete.tsx
- src/components/SearchBox/options/geocoder.tsx
- src/components/SearchBox/useGetOnSelected.ts
- src/components/SearchBox/useGetOptions.tsx
Refactoring in #999 broke the geocoder search. The debounced function never returned any data.
> SearchBox: bugfix - geocoder always loading

- src/components/FeaturePanel/Climbing/GradeSystemSelect.tsx
- src/components/FeaturePanel/Climbing/RouteDistribution.tsx
- src/components/FeaturePanel/Climbing/utils/grades/gradeData.ts
- src/components/FeaturePanel/MemberFeatures/MemberFeatures.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
- src/services/tagging/climbing.ts
> GradeSystemSelect: Improve select

- src/components/FeaturePanel/Climbing/useGetHandleSave.tsx
- src/components/FeaturePanel/EditDialog/EditDialog.tsx
- src/components/FeaturePanel/EditDialog/useEditItems.tsx
- src/components/utils/OsmAuthContext.tsx
- src/services/__tests__/osmApi.fixture.ts
- src/services/helpers.ts
- src/services/osm/auth/api.ts
- src/services/osm/auth/authFetch.ts
- src/services/osm/auth/editCrag.ts
- src/services/osm/auth/stringifyDomXml.ts
- src/services/osm/auth/user.ts
- src/services/osm/auth/xmlHelpers.ts
- src/services/osm/auth/xmlTypes.ts
- src/services/osm/osmApiAuth.ts
- src/services/osm/osmToFeature.ts
- src/services/types.ts
- add `nodes` to osmToFeature, to Feature and to DataItem for **osm way**
- preparation for uploadDiff
> osmApi: refactoring + add way nodes

- src/components/FeaturePanel/Climbing/ClimbingGradesTable.tsx
- src/components/FeaturePanel/Climbing/GradeSystemSelect.tsx
- src/components/FeaturePanel/Climbing/RouteDistribution.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListDndContent.tsx
- src/components/FeaturePanel/ClimbingRouteGrade.tsx
- src/components/utils/UserSettingsContext.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
- src/services/tagging/climbing.ts
> GradeSystemSelect: Improve UX

- src/components/FeaturePanel/EditDialog/useGetHandleSave.tsx
- src/services/osm/auth/editCrag.ts
- src/services/osm/auth/osmApiAuth.ts
> osmApi: refactoring - move osmApiAuth

- src/components/FeaturePanel/Climbing/ClimbingGradesTable.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> GradeTable: Improve UX

- src/components/FeaturePanel/Climbing/FeaturePanelClimbingGuideInfo.tsx
- src/components/FeaturePanel/Climbing/PanelLabel.tsx
- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListDndContent.tsx
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/FeaturePanel/FeatureHeading.tsx
- src/components/FeaturePanel/FeatureImages/FeatureImages.tsx
- src/components/FeaturePanel/FeatureImages/Image/Image.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
- src/components/FeaturePanel/FeaturedTag.tsx
- src/components/FeaturePanel/ParentLink.tsx
- src/components/FeaturePanel/QuickActions/QuickActions.tsx
- src/components/FeaturePanel/helpers/PoiDescription.tsx
- src/components/utils/PanelHelpers.tsx
- src/helpers/TitleAndMetaTags.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> SEO: Improve SEO

- src/components/FeaturePanel/EditDialog/useEditItems.tsx
- src/components/FeaturePanel/Properties/renderTag.tsx
Removed unnecessary complexity.
> EditDialog: refactor `updateAllMemberLabels()`

- src/services/osm/offlineItems.tsx
Missing properties for offlineItems.
> FeaturePanel: fix SSR for mocked node

- src/components/FeaturePanel/EditDialog/useEditItems.tsx
The parent items were not added (beacuse .concat returns new array).
> EditDialog: fix convertToRelation()

- src/components/FeaturePanel/CragsInArea.tsx
- src/helpers/TitleAndMetaTags.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> CragsInArea: Add badge with info

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/PresetSearchBox.tsx
- src/services/tagging/ourPresets.ts
> EditDialog: don't show unrelated empty types

- src/components/FeaturePanel/EditDialog/itemsHelpers.ts
- src/services/osm/fetchParentFeatures.ts
- src/services/osm/fetchWays.ts
- src/services/osm/types.ts
also fix fetchFreshItem with empty tags
> EditDialog: fix convertToRelation for new node

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MembersEditor.tsx
> EditDialog: refactor MembersEditor - extract inner components

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ParentsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/helpers.tsx
- src/components/FeaturePanel/EditDialog/EditContent/useHandleItemClick.tsx
> EditDialog: refactor useHandleItemClick()

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ConvertNodeToRelation.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureRow.tsx
- src/components/FeaturePanel/EditDialog/EditContent/useHandleItemClick.tsx
Also fixed MembersEditor showing for all relations + for convertible nodes
> EditDialog: extract ConvertNodeToRelation from MembersEditor

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ParentsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureRow.tsx
> EditDialog: refactor ParentsEditor

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/LocationEditor/useStaticMarkers.tsx
Unbelievably - fixed by Copilot Agent mode just based on the description in #1030
Viva AI :)
Fixes #1030
> EditDialog: fix react error in EditFeatureMap

- src/components/FeaturePanel/EditDialog/itemsHelpers.ts
- src/services/osm/osmApi.ts
It was easier to fix the one broken function, than to remove all the occurences.
> osmApi: fix undelete

- src/components/FeaturePanel/EditDialog/EditContent/EditContent.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ItemEditSection.tsx
| 1 | 2 |
|--|--|
| ![image](https://github.com/user-attachments/assets/ecd46a20-0849-4e69-a1fc-5dfc6ad5a560) | ![image](https://github.com/user-attachments/assets/2f78b249-6217-4204-9f0c-a163fc653460) |
> EditDialog: hide form when item is `toBeDeleted`

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ItemHeading.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ItemsTabs.tsx
https://github.com/emotion-js/emotion/issues/2193
> EditDialog: fix warnings - styled transient props

- src/components/HomepagePanel/HomepageOpenClimbing.tsx
> Homepage: Fix header on mobile

- eslint-local-rules.js
- src/components/FeaturePanel/PublicTransport/routes/LineNumber.tsx
- src/components/SearchBox/optionsPopper.tsx
> general: eslint rule for transient props - fix other files

- pages/_app.tsx
- pages/_document.tsx
- src/helpers/TitleAndMetaTags.tsx
> SEO: Fix head issues

- src/components/FeaturePanel/Climbing/RouteDistribution.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
> FeaturePanel: RouteDistribution without condition in feature panel

- src/components/FeaturePanel/Climbing/ClimbingGradesTable/ClimbingGradesTable.tsx
- src/components/FeaturePanel/Climbing/ClimbingGradesTable/ClimbingGradesTableSettings.tsx
- src/components/FeaturePanel/Climbing/GradeSystemSelect.tsx
- src/components/FeaturePanel/Climbing/utils/useVisibleGradeSystems.ts
> GradeSystemSelect: Show visible grades by default

- src/components/LayerSwitcher/Overlays.tsx
- src/components/Map/MapFooter/ClimbingLegend.tsx
- src/components/Map/climbingTiles/climbingLayers.ts
- src/components/Map/climbingTiles/climbingLayers/climbingLayers.ts
- src/components/Map/climbingTiles/climbingLayers/groupsLayer.ts
- src/components/Map/climbingTiles/climbingLayers/helpers.ts
- src/components/Map/climbingTiles/climbingLayers/routes.ts
- src/components/Map/climbingTiles/climbingLayers/routesLines.ts
- src/components/Map/climbingTiles/climbingLayers/routesPoints.ts
- src/components/Map/climbingTiles/climbingTilesSource.ts
- src/components/Map/climbingTiles/consts.ts
- src/components/Map/styles/layers/climbingLayers.ts
- src/services/osm/consts.ts
> climbingTiles: layers refactoring

- src/components/Map/climbingTiles/climbingLayers/climbingLayers.ts
- src/components/Map/climbingTiles/climbingLayers/groupsLayer.ts
- src/server/climbing-tiles/getClimbingTile.ts
https://openclimbing.org/#11.43/50.0559/14.4153
> climbingTiles: add `gym` to the map

- src/components/Map/climbingTiles/climbingLayers/climbingLayers.ts
- src/components/Map/climbingTiles/climbingLayers/groupsLayer.ts
- src/server/climbing-tiles/getClimbingTile.ts
- src/server/climbing-tiles/refreshClimbingTiles.ts
- src/services/osm/osmApi.ts
> climbingTiles: add `ferrata` to the map

- src/components/FeaturePanel/FeaturedTag.tsx
- src/components/FeaturePanel/renderers/ScaleRenderer.tsx
- src/locales/vocabulary.js
- src/services/tagging/featuredKeys.ts
> FeaturePanel: add via_ferrata_scale + sac_scale

- package.json
- src/components/Map/styles/outdoorStyle.ts
- yarn.lock
maplibre + get rid of "steps" function in outdoor style
Followup to https://github.com/zbycz/osmapp/pull/1089
> general: update dependencies - maplibre-gl to 5.5.0

- src/components/Map/styles/outdoorStyle.ts
| old | new |
|--|--|
|![Screenshot 2025-06-03 at 15 55 06](https://github.com/user-attachments/assets/c05cd1a2-a714-4812-a0f0-0bb4a58d33a1) | ![Screenshot 2025-06-03 at 15 55 03](https://github.com/user-attachments/assets/e4439939-e69f-4cd3-93a7-6c5fbfbc6c44) |
> layers: use track for outdoorStyle

- src/components/FeaturePanel/FeaturedTag.tsx
- src/components/FeaturePanel/Properties/renderTag.tsx
- src/components/SearchBox/options/osm.tsx
https://github.com/zbycz/osmapp/issues/1096
node/2510246602
https://overpass-turbo.eu/s/25Ji
> FeaturePanel: render links for each ";" separated values

- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/FeaturePanel/Climbing/utils/useGetMachineFactory.ts
> Climbing: Fix panning bug

- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
> Climbing: Add hiding routes when press 'h' in ClimbingView

- src/components/FeaturePanel/Climbing/ClimbingCragDialogHeader.tsx
- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/utils/photo.ts
- src/components/FeaturePanel/Climbing/utils/useClimbingViewShortcuts.ts
- src/components/FeaturePanel/Climbing/utils/usePhotoChange.ts
> Climbing: Add shortcuts for switching photos

- src/components/FeaturePanel/Climbing/utils/grades/gradeData.ts
- src/services/tagging/climbing.ts
> Climbing: Add polish grading system

- src/components/LayerSwitcher/osmappLayers.tsx
- src/components/Map/BrowserMap.tsx
- src/components/Map/behaviour/useUpdateStyle.tsx
- src/components/Map/climbingTiles/climbingTilesSource.ts
- src/components/Map/helpers.ts
- src/services/mapStorage.ts
Fixes #771
Thanks to some resolution in planetiler project, i decided to let go my "standardization effort" to use the 0/1/4 schema everywhere, and just adapt for OpenFreeMap only. :-)
> Map: make OpenFreeMap clickable

- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/SearchBox.tsx
- src/components/SearchBox/options/geocoder.tsx
- src/components/SearchBox/useHandleQuery.tsx
Exploration what is needed to achieve search param in URL (like in #988) cc @amenk
For simplicity the URL is only synced when no panel is opened. 
There is one refactoring needed in geocoder.ts, but this PR is opened to explore possible bugs. Feedback welcomed. Also if anyone wants to take it over. 🙂
> SearchBox: sync with url parameter `?q=...`

- src/components/LayerSwitcher/osmappLayers.tsx
> LayerSwitcher: Add grayscale map for CZ

- src/components/Directions/DirectionsForm.tsx
> Directions: Fix directions order

- src/components/SearchBox/AutocompleteInput.tsx
- src/components/SearchBox/useHandleQuery.tsx
Sometimes letters were removed while writing, and sync to URL occured. (But why not always? 🤷)
> SearchBox: fix `?q=...` sometimes crippling user input

- src/services/images/getImageFromApi.ts
> images: fix loading too many images for Wikimedia Category

- src/server/climbing-tiles/overpass/overpassToGeojsons.ts
- src/server/climbing-tiles/refreshClimbingTiles.ts
- src/server/climbing-tiles/refreshClimbingTilesHelpers.ts
```
Skipping relation without members: relation/19330166
Skipping record without geometry, mapid: 193024184  --> relation/19302418
```
> climbingTiles: fix relations without members or geometry

- src/components/FeaturePanel/Climbing/Editor/RoutesEditor.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
- src/components/FeaturePanel/Climbing/TransformWrapper.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
> Climbing: fix cancel route while panning

- src/components/FeaturePanel/EditDialog/EditContent/ItemsTabs.tsx
> Climbing: Fix scrollable tabs

- src/components/SearchBox/renderInputFactory.tsx
> SearchBox: prevent Enter key to close autocomplete

- package.json
- public/oauth-token.html
- yarn.lock
https://github.com/openstreetmap/openstreetmap-website/commit/2ff4d6
> OsmAuth: fix broken login due to OSM.org changes

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MajorKeysEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/WikimediaCommonsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/helpers.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> EditDialog: extract WikimediaCommonsEditor + paste URL

- src/components/FeaturePanel/Climbing/CragsInAreaFilter.tsx
- src/components/FeaturePanel/Climbing/CragsInAreaSort.tsx
- src/components/FeaturePanel/CragsInArea.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> Climbing: Update crag filter 2

- src/components/Directions/DirectionsBox.tsx
- src/components/FeaturePanel/Climbing/CragsInAreaFilter/CragsInAreaFilter.tsx
- src/components/FeaturePanel/Climbing/CragsInAreaSort/CragsInAreaSort.tsx
- src/components/FeaturePanel/Climbing/GradeSystemSelect.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/AutocompleteSelect.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/GradeSelect.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MajorKeysEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ItemEditSection.tsx
- src/components/FeaturePanel/EditDialog/EditDialog.tsx
- src/components/HomepagePanel/Homepage.tsx
- src/components/SearchBox/options/climbing.tsx
- src/components/SearchBox/options/coords.tsx
- src/components/SearchBox/options/geocoder.tsx
- src/components/SearchBox/options/osm.tsx
- src/components/SearchBox/options/overpass.tsx
- src/components/SearchBox/options/preset.tsx
- src/components/SearchBox/options/stars.tsx
- src/components/SearchBox/utils.tsx
> App: Refactoring and fix simple bugs

- src/components/FeaturePanel/Climbing/ClimbingTypeBadge.tsx
> Climbing: Add climbing type badges

- src/components/FeaturePanel/Climbing/Editor/MouseTrackingLine.tsx
- src/components/FeaturePanel/Climbing/Editor/PathWithBorder.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutePath.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteWithLabel.tsx
Only ide refacs + ...props removed
> climbing: refactor - add Props, remove spreading in RoutePath

- src/components/Map/climbingTiles/climbingLayers/routesLines.ts
- src/components/Map/climbingTiles/climbingLayers/routesPoints.ts
- src/server/climbing-tiles/overpass/overpassToGeojsons.ts
> Climbing: Add grade to climbing tiles name

- src/components/FeaturePanel/Climbing/ClimbingGradesTable/ClimbingGradesTableBody.tsx
- src/components/FeaturePanel/Climbing/Editor/PathWithBorder.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteDifficulty.tsx
- src/components/FeaturePanel/Climbing/RouteDifficultyBadge.tsx
- src/components/FeaturePanel/Climbing/RouteDistribution.tsx
- src/components/FeaturePanel/Climbing/utils/grades/routeGrade.ts
- src/components/FeaturePanel/FeatureImages/PathsSvg.tsx
> Climbing: Refactor getDifficultyColor

- src/components/FeaturePanel/Climbing/RouteDistribution.tsx
> Climbing: Fix distribution in crags without route

- src/components/Map/climbingTiles/climbingLayers/routesLines.ts
- src/components/Map/climbingTiles/climbingLayers/routesPoints.ts
- src/server/climbing-tiles/overpass/overpassToGeojsons.ts
- src/services/tagging/climbing/routeGrade.ts
> climbingTiles: introduce route colors (lentilky)

- src/components/Map/climbingTiles/climbingLayers/groupsLayer.ts
- src/components/Map/climbingTiles/climbingLayers/routesLines.ts
- src/components/Map/climbingTiles/climbingLayers/routesPoints.ts
> Climbing: Update formatting on the map

- src/components/FeaturePanel/Climbing/CragsInAreaFilter/CragsInAreaFilter.tsx
- src/components/FeaturePanel/Climbing/CragsInAreaFilter/utils/filterCrag.tsx
- src/components/FeaturePanel/Climbing/CragsInAreaFilter/utils/useCragsInAreaFilter.tsx
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/utils/UserSettingsContext.tsx
> Climbing: Add filter to userSettings

- src/components/FeaturePanel/Climbing/CragsInAreaFilter/CragsInAreaFilter.tsx
- src/components/FeaturePanel/Climbing/CragsInAreaFilter/GradeFilter.tsx
- src/components/FeaturePanel/Climbing/CragsInAreaFilter/utils/filterCrag.tsx
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/utils/userSettings/UserSettingsContext.tsx
- src/components/utils/userSettings/useClimbingFilter.tsx
> Climbing: Fix conversion while changing grade system in filter

- src/components/FeaturePanel/Climbing/CragsInAreaFilter/CragsInAreaFilter.tsx
- src/components/FeaturePanel/Climbing/CragsInAreaFilter/GradeFilter.tsx
- src/components/FeaturePanel/Climbing/CragsInAreaFilter/MinimumRoutesFilter.tsx
- src/components/FeaturePanel/CragsInArea.tsx
- src/components/utils/userSettings/getClimbingFilter.tsx
- reset exported from gradeFilter
- refactor - use context -> remove props
- refactor -get rid of `gradeToOriginalIndexMap`
> climbingFilter: fix reset + 2 refactors

- src/components/Map/climbingTiles/climbingTilesSource.ts
- src/components/SearchBox/options/climbing.tsx
- src/types.ts
Broken after v2 redesign #1216 
Fixed:
> SearchBox: fix climbing icons

- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
> Climbing: Filter routes in crag

- src/components/FeaturePanel/Climbing/ClimbingBadges.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ClimbingMultiValues.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> Climbing: Add slippery hazard

- src/components/FeaturePanel/Climbing/Editor/InteractivePath.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutePath.tsx
Also segmentIndex moved from onMove to onClick - allowed us to get rid of another temp state.
> climbing: refactor - extract InteractivePath

- src/components/FeaturePanel/Climbing/Editor/InteractivePath.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesEditor.tsx
- src/components/FeaturePanel/Climbing/utils/mousePositionUtils.ts
- src/components/FeaturePanel/Climbing/utils/useGetMachineFactory.ts
Allowed to remove the getMidpointPosition() helper
> climbing: refactor - getPositionInImageFromMouse() takes MouseEvent

- src/components/FeaturePanel/Climbing/Editor/RoutesEditor.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
onPointerMove is universal.
The onTouchMove was not returning clientX+clientY, but touches array. Found out thanks to types 🙈
> climbing: fix move of point on mobile

- src/components/FeaturePanel/Climbing/ClimbingCragDialog.tsx
- src/components/FeaturePanel/Climbing/ClimbingEditorHelperText.tsx
- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/Editor/InteractivePath.tsx
- src/components/FeaturePanel/Climbing/Editor/PointMenu.tsx
- src/components/FeaturePanel/Climbing/Editor/PointTypeButtons.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteFloatingMenu.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteMarks.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteNumber.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutePath.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
- src/components/FeaturePanel/Climbing/Editor/StartPoint.tsx
- src/components/FeaturePanel/Climbing/Editor/utils.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListDndContent.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/FeaturePanel/Climbing/utils/useStateMachine.ts
> climbing: refactor - use `machine` instead of `getMachine()`

- src/components/FeaturePanel/Climbing/RouteDistribution.tsx
- src/components/MyTicksPanel/MyTicksGraphs/MyTicksGraphs.tsx
> Climbing: Prop for disable grouping in RouteDistribution

- src/components/HomepagePanel/Homepage.tsx
https://github.com/zbycz/osmapp/pull/1187#issuecomment-3106397844
Fixed back as it was before.
| before | now |
|--|--|
| <img width="400" height="316" alt="image" src="https://github.com/user-attachments/assets/85016a59-344e-47b0-8f8e-c30e991b5139" /> |  <img width="399" height="429" alt="image" src="https://github.com/user-attachments/assets/6906b5a4-37d9-409b-b3f3-968c47336856" /> |
> Homepage: fix broken Grid

- src/components/FeaturePanel/Climbing/ClimbingBadges.tsx
- src/components/FeaturePanel/FeaturePanel.tsx
To conform with this comment above:
```
// ------------------------------------------------------------------------
// Conditional components should have if(feature.tags.xxx) check at the beginning
// ------------------------------------------------------------------------
```
> FeaturePanel: refactor - introduce PanelClimbingBadges

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MembersEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ParentsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/useHandleItemClick.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> EditDialog: fix crash - openAll with no members + refactors

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/MajorKeysEditor.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
- src/locales/zh-CN.js
- src/locales/zh-HK.js
- src/locales/zh-TW.js
> Climbing: Fix length

- src/components/FeaturePanel/FeatureImages/Image/Image.tsx
- src/components/FeaturePanel/FeatureImages/Image/helpers.tsx
eg http://localhost:3000/node/11580081580 or https://openclimbing.org/relation/19439203
> images: fix cursor on non-clickable images

- src/components/Directions/DirectionsContext.tsx
- src/components/Directions/ModeToggler.tsx
- src/components/Directions/routing/handleRouting.ts
- src/components/Directions/useGetOnSubmit.tsx
- src/components/FeaturePanel/Climbing/CragsInAreaSort/CragsInAreaSort.tsx
- src/components/FeaturePanel/Climbing/Filter/FilterPopover.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/FeaturePanel/Climbing/useGetHandleSave.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/LocationEditor/useStaticMarkers.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/OpeningHoursEditor/AddSlotButton.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/OpeningHoursEditor/TimeSlot.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/OpeningHoursEditor/useGetBlurValidation.tsx
- src/components/FeaturePanel/EditDialog/EditContext.tsx
- src/components/FeaturePanel/FeaturePanelFooter.tsx
- src/components/FeaturePanel/helpers/EditDialogContext.tsx
- src/components/SearchBox/options/geocoder.tsx
- src/components/SearchBox/renderInputFactory.tsx
- src/components/SearchBox/useHandleQuery.tsx
- src/components/utils/FeatureContext.tsx
- src/components/utils/userSettings/UserSettingsContext.tsx
- src/components/utils/userSettings/getClimbingFilter.tsx
- src/helpers/theme.tsx
> general: types - use `Setter<T>` consistently

- src/components/Directions/Directions.tsx
- src/components/Map/HamburgerMenu/HamburgerMenu.tsx
- src/components/Map/HamburgerMenu/LoginIconButton.tsx
- src/components/Map/HamburgerMenu/UserMenu.tsx
- hover for logout
- maxwidth+ellipsis on username + without uppercase
- don't close panel on login/logout
- swap dark/light icon
- also: add seo title for directions lookup
> HamburgerMenu: minor tweaks, add hover, etc

- src/components/Map/Map.tsx
- src/components/Map/MapFooter/ClimbingLegend.tsx
- src/components/Map/MapFooter/MapFooter.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> ClimbingLegend: Update legend

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ClimbingEditor/ClimbingEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/TagsEditor/TagsEditor.tsx
- src/components/utils/icons/Maki.tsx
> EditDialog: Update icon alignment for ClimbingEditor

- src/components/FeaturePanel/Climbing/ClimbingCragDialog.tsx
- src/components/FeaturePanel/Climbing/ClimbingView.tsx
- src/components/FeaturePanel/Climbing/RouteList/RouteListDndContent.tsx
- src/components/FeaturePanel/Climbing/utils/useReplacePhotoIfNeeded.tsx
- src/components/HomepagePanel/UserSettingsDialog.tsx
- src/components/utils/userSettings/UserSettingsContext.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> Climbing: Show related photo by route click in ClimbingView

- src/components/FeaturePanel/Climbing/Editor/useFloatingMenuShortcuts.tsx
- src/components/FeaturePanel/Climbing/RouteDistribution.tsx
- src/components/FeaturePanel/Climbing/utils/useClimbingViewShortcuts.ts
> Climbing: Update shortcuts

- src/components/FeaturePanel/Climbing/Editor/Points/Point.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
- src/components/FeaturePanel/Climbing/TransformWrapper.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
- src/components/FeaturePanel/Climbing/utils/findCloserPoint.ts
> Climbing: Fix not adding points while panning

- src/components/FeaturePanel/Climbing/Editor/RoutesLayer.tsx
- src/components/FeaturePanel/Climbing/TransformWrapper.tsx
- src/components/FeaturePanel/Climbing/contexts/ClimbingContext.tsx
> Climbing: Fix zooming bug

- src/components/Map/climbingTiles/climbingTilesSource.ts
- src/types.ts
Forgot to update the layers in #1310 to use `name` as well 😅
> climbingTiles: fix skeleton to show name - part 3

- src/components/FeaturePanel/EditDialog/EditContent/EditDialogActions.tsx
- src/locales/vocabulary.js
- src/services/osm/auth/__tests__/getDiffXml.test.ts
- src/services/osm/auth/getDIffXml.ts
- src/services/osm/auth/osmApiAuth.ts
- src/services/osm/auth/xmlTypes.ts
> EditDialog: add osmChange file download

- src/services/osm/auth/osmApiAuth.ts
- src/services/osm/getFirstExistingId.ts
From EditDataItem to DataItem
Enabler for #1326
> osmApi: refactor saveChanges() to DataItem

- src/components/FeaturePanel/Climbing/Editor/InteractivePath.tsx
- src/components/FeaturePanel/Climbing/Editor/MouseTrackingLine.tsx
- src/components/FeaturePanel/Climbing/Editor/PathWithBorder.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteLine.tsx
- src/components/FeaturePanel/Climbing/Editor/RoutePath.tsx
- src/components/HomepagePanel/HomepageOpenClimbing.tsx
- src/helpers/TitleAndMetaTags.tsx
- src/locales/cs.js
- src/locales/fr.js
> Climbing: Refactor SVG path to line in Editor

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ConvertNodeToRelation.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureRow.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ItemEditSection.tsx
- src/components/FeaturePanel/EditDialog/EditContent/useHandleItemClick.tsx
- src/components/FeaturePanel/EditDialog/useEditItems.tsx
- add member doesnt open the new tab (not sure if ever needed) -- TODO related to #1333
- padding after accordeons
- move helper to be used by #1338
> EditDialog: minor tweaks + refactor

- src/components/FeaturePanel/Climbing/ClimbingCragDialog.tsx
- src/components/FeaturePanel/Climbing/ClimbingView.tsx
> Climbing: Fix recalculation height while climbing footer appeared

- src/components/FeaturePanel/EditDialog/EditContent/EditDialogActions.tsx
- src/components/FeaturePanel/EditDialog/EditContent/ItemsTabs.tsx
- src/components/FeaturePanel/EditDialog/__tests__/useEditItems.convertToRelationFactory.test.tsx
- src/components/FeaturePanel/EditDialog/__tests__/useEditItems.test.tsx
- src/components/FeaturePanel/EditDialog/createNoteText.ts
- src/components/FeaturePanel/EditDialog/itemsHelpers.ts
- src/components/FeaturePanel/EditDialog/useEditItems.tsx
- src/components/FeaturePanel/EditDialog/useGetHandleSave.tsx
- src/services/osm/auth/__tests__/getDiffXml.test.ts
Also:
- submits only the modified items
- disables submit button
- and fixed createNote
> EditDialog: add modified badge

- src/components/Climbing/Climbing.tsx
- src/components/FeaturePanel/Climbing/ClimbingCragDialog.tsx
- src/components/FeaturePanel/Climbing/utils/photo.ts
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ClimbingEditor/ClimbingEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ClimbingEditor/DrawClimbingRoutesBanner.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/ParentsEditor.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/useGetParents.tsx
- src/components/FeaturePanel/EditDialog/EditDialog.tsx
- src/components/FeaturePanel/FeatureImages/Image/helpers.tsx
- src/locales/cs.js
- src/locales/vocabulary.js
> EditDialog: Add Save & Draw

- src/server/climbing-tiles/buildTileGeojson.ts
- src/server/climbing-tiles/db.sql
- src/server/climbing-tiles/db.ts
- src/server/climbing-tiles/overpass/overpassToGeojsons.ts
- src/server/climbing-tiles/overpass/types.ts
- src/server/climbing-tiles/refreshClimbingTilesHelpers.ts
- src/types.ts
We take all areas, and write parentId to every member.
Works also for areas of areas, etc. (relation/19302417)
---
0/0/0 size:
from 513 kB
to 514 kB
> climbingTiles: add parentId

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/AddMemberForm.tsx
- src/components/FeaturePanel/EditDialog/EditContent/useHandleItemClick.tsx
- src/components/FeaturePanel/EditDialog/context/__tests__/useEditItems.convertToRelationFactory.test.tsx
- src/components/FeaturePanel/EditDialog/context/convertToRelationFactory.tsx
- src/components/FeaturePanel/EditDialog/context/useEditItems.tsx
- src/components/FeaturePanel/EditDialog/context/utils.ts
> EditDialog: refactor - extract utils

- src/components/HomepagePanel/UserSettingsDialog.tsx
- src/services/fetchCache.ts
> general: add store_requests_to_local_storage setting

- pages/_app.tsx
- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
- src/components/FeaturePanel/Climbing/Ticks/AddTickButton.tsx
- src/components/FeaturePanel/Climbing/Ticks/TicksContext.tsx
- src/components/Map/MapFooter/ClimbingLegend.tsx
- src/components/Map/MapFooter/MapFooter.tsx
- src/helpers/GlobalStyle.tsx
> Climbing: Refactor EditTickModal

- src/components/FeaturePanel/helpers/addWebsiteForClimbingFeatures.ts
> Climbing: Fix tag entries for adding website

- src/components/FeaturePanel/EditDialog/EditContent/EditDialogActions.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/helpers.tsx
Also add icon to ShowAllButton
> EditDialog: show "Download osmChange" only for modified

- pages/api/climbing-ticks/[id].ts
- pages/api/climbing-ticks/index.ts
- src/components/FeaturePanel/Climbing/EditTickModal.tsx
- src/components/FeaturePanel/Climbing/Editor/RouteNumber.tsx
- src/components/FeaturePanel/Climbing/RouteList/ClimbingRouteTableRow.tsx
- src/components/FeaturePanel/Climbing/RouteTickRow.tsx
- src/components/FeaturePanel/Climbing/TickMoreButton.tsx
- src/components/FeaturePanel/Climbing/Ticks/AddTickButton.tsx
- src/components/FeaturePanel/Climbing/Ticks/MyRouteTicks.tsx
- src/components/FeaturePanel/Climbing/YellowedBadge.tsx
- src/components/FeaturePanel/Climbing/useMoreMenu.tsx
- src/components/MyTicksPanel/MyTicksPanel.tsx
- src/components/MyTicksPanel/MyTicksRow.tsx
- src/components/utils/TicksContext.tsx
- src/server/climbing-tiles/db.ts
- src/services/my-ticks/myTicksApi.ts
- src/services/my-ticks/ticks.ts
- src/services/tagging/climbing/gradeSystems.ts
Each commit is a feature commit. Merged as is.
> ClimbingTicks: persist to DB

- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/LocationEditor/EditFeatureMap.tsx
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/LocationEditor/useInitEditFeatureMap.ts
- src/components/FeaturePanel/EditDialog/EditContent/FeatureEditSection/LocationEditor/useUpdateCenter.ts
- src/components/Map/BrowserMap.tsx
- src/components/Map/behaviour/PersistedScaleControl.ts
- src/components/Map/behaviour/useInitMap.tsx
- src/helpers/GlobalStyle.tsx
> EditDialog: Add scale to EditFeatureMap

- src/components/FeaturePanel/Climbing/Filter/FilterPopover.tsx
- src/components/FeaturePanel/Climbing/Filter/GradeFilter.tsx
> FilterPopover: refactor + showDefaultOnButton

- src/components/Map/MapFilter/MapFilter.tsx
> FilterPopover: refactor - extract MapfilterButton
